/**
 * Export Template Registry
 *
 * Built-in and custom export templates for the Story Export feature.
 * Custom templates can be registered at runtime via registerExportTemplate().
 * Marketplace templates (Phase 6) will use the same mechanism.
 */

export interface ExportTemplateField {
  key: string;
  label: string;
}

export interface ExportTemplate {
  /** Unique template identifier */
  id: string;
  /** Human-readable name */
  name: string;
  /** Short description */
  description: string;
  /** Output format: text, json, or custom string for community formats */
  format: string;
  /** Whether this template is built-in (cannot be unregistered) */
  builtin: boolean;
  /**
   * Render function: takes export data and returns formatted string content.
   * The data shape matches the engine's DataExport response.
   */
  render: (data: ExportData) => string;
}

/** Shape of data passed to export template render functions. */
export interface ExportData {
  echoName: string;
  whatIfPrompt: string;
  persona: string;
  diaryEntries: Array<{
    tick: number;
    content: string;
    created_at: string;
    image_url?: string | null;
  }>;
  lifeEvents: Array<{
    tick: number;
    event_type: string;
    description: string;
    created_at: string;
  }>;
  relationships: Array<{
    target_name: string;
    type: string;
    sentiment: number;
  }>;
}

// SOURCE: crates/safety/src/disclaimer.rs::AI_GENERATED_CONTENT_DISCLAIMER
// Verbatim mirror of the canonical Rust constant. Cross-language byte-
// identicality is enforced by
// crates/safety/tests/disclaimer_canonical_consistency.rs — when this
// string changes, the regression test fails until the Rust + Worker
// + client copies are updated together. The literal MUST stay as a
// single contiguous string (no `+` concatenation) so the regression
// test's substring scan succeeds regardless of where prettier wraps
// the surrounding line.
const AI_DISCLAIMER =
  'This content was autonomously generated by an AI simulation and does not represent real events or the views of any real person.';

// --- Built-in templates ---

const textTemplate: ExportTemplate = {
  id: 'builtin-text',
  name: 'Plain Text',
  description:
    'Simple text format with sections for diary, events, and relationships.',
  format: 'text',
  builtin: true,
  render: (data) => {
    const lines: string[] = [];
    lines.push(`# The Story of ${data.echoName}`);
    lines.push('');
    lines.push(`> ${AI_DISCLAIMER}`);
    lines.push('');
    lines.push(`## What If`);
    lines.push(data.whatIfPrompt);
    lines.push('');
    lines.push(`## Persona`);
    lines.push(data.persona);
    lines.push('');
    lines.push(`## Diary`);
    for (const entry of data.diaryEntries) {
      lines.push(`### Tick ${entry.tick} (${entry.created_at})`);
      lines.push(entry.content);
      if (entry.image_url) {
        lines.push(`[Image: ${entry.image_url}]`);
      }
      lines.push('');
    }
    lines.push(`## Life Events`);
    for (const event of data.lifeEvents) {
      lines.push(
        `- [Tick ${event.tick}] ${event.event_type}: ${event.description}`,
      );
    }
    lines.push('');
    lines.push(`## Relationships`);
    for (const rel of data.relationships) {
      lines.push(
        `- ${rel.target_name} (${rel.type}, sentiment: ${rel.sentiment})`,
      );
    }
    return lines.join('\n');
  },
};

const jsonTemplate: ExportTemplate = {
  id: 'builtin-json',
  name: 'JSON',
  description: 'Machine-readable JSON format for tools and integrations.',
  format: 'json',
  builtin: true,
  render: (data) => {
    return JSON.stringify(
      {
        disclaimer: AI_DISCLAIMER,
        echo: {
          name: data.echoName,
          what_if_prompt: data.whatIfPrompt,
          persona: data.persona,
        },
        diary_entries: data.diaryEntries,
        life_events: data.lifeEvents,
        relationships: data.relationships,
      },
      null,
      2,
    );
  },
};

const timelineTemplate: ExportTemplate = {
  id: 'builtin-timeline',
  name: 'Timeline',
  description: 'Chronological interleaving of diary entries and life events.',
  format: 'text',
  builtin: true,
  render: (data) => {
    const lines: string[] = [];
    lines.push(`# Timeline: ${data.echoName}`);
    lines.push('');
    lines.push(`> ${AI_DISCLAIMER}`);
    lines.push('');

    type TimelineItem = { tick: number; type: 'diary' | 'event'; text: string };
    const items: TimelineItem[] = [];
    for (const entry of data.diaryEntries) {
      items.push({ tick: entry.tick, type: 'diary', text: entry.content });
    }
    for (const event of data.lifeEvents) {
      items.push({
        tick: event.tick,
        type: 'event',
        text: `[${event.event_type}] ${event.description}`,
      });
    }
    items.sort((a, b) => a.tick - b.tick);

    for (const item of items) {
      const prefix = item.type === 'diary' ? '📖' : '⚡';
      lines.push(`**Tick ${item.tick}** ${prefix}`);
      lines.push(item.text);
      lines.push('');
    }
    return lines.join('\n');
  },
};

// --- Registry ---

const registry: ExportTemplate[] = [
  textTemplate,
  jsonTemplate,
  timelineTemplate,
];

/** Get all registered export templates. */
export function getExportTemplates(): readonly ExportTemplate[] {
  return registry;
}

/** Get a specific template by id. */
export function getExportTemplate(id: string): ExportTemplate | undefined {
  return registry.find((t) => t.id === id);
}

/** Register a custom export template. Throws if id conflicts with a built-in. */
export function registerExportTemplate(template: ExportTemplate): void {
  const existing = registry.find((t) => t.id === template.id);
  if (existing?.builtin) {
    throw new Error(`Cannot override built-in template "${template.id}"`);
  }
  // Replace or append
  const idx = registry.findIndex((t) => t.id === template.id);
  if (idx >= 0) {
    registry[idx] = template;
  } else {
    registry.push(template);
  }
}

/** Unregister a custom export template. Built-in templates cannot be removed. */
export function unregisterExportTemplate(id: string): boolean {
  const idx = registry.findIndex((t) => t.id === id);
  if (idx < 0) return false;
  if (registry[idx].builtin) {
    throw new Error(`Cannot unregister built-in template "${id}"`);
  }
  registry.splice(idx, 1);
  return true;
}
