/**
 * API response/request types matching the Rust engine.
 *
 * Enum types are re-exported from generated.ts (auto-generated by Specta from Rust).
 * Struct/interface types here represent API response shapes, which may include
 * computed fields (can_edit, can_delete, etc.) not present in the Rust storage model.
 *
 * For the full Rust storage model, see generated.ts directly.
 * To regenerate: `cargo run --bin generate-types`
 */

// Import enum types from generated.ts — single source of truth
import type {
  AccountStatus as _AccountStatus,
  AccountType as _AccountType,
  CancelRequest as _CancelRequest,
  ChannelType as _ChannelType,
  CommitRequest as _CommitRequest,
  ConflictStyle as _ConflictStyle,
  ConsentType as _ConsentType,
  ConversationRole as _ConversationRole,
  CryptoBillingProvider as _CryptoBillingProvider,
  DowngradeSession as _DowngradeSession,
  DowngradeSessionState as _DowngradeSessionState,
  DowngradeSessionView as _DowngradeSessionView,
  DunningPhase as _DunningPhase,
  EchoResponse as _EchoResponse,
  EconomicModel as _EconomicModel,
  EchoRelationshipType as _EchoRelationshipType,
  EchoStatus as _EchoStatus,
  ExportFormat as _ExportFormat,
  ExportStatus as _ExportStatus,
  GlobalEventStatus as _GlobalEventStatus,
  GlobalEventType as _GlobalEventType,
  LifeEventType as _LifeEventType,
  LocationType as _LocationType,
  MarketplaceCategory as _MarketplaceCategory,
  MarketplaceItem as _MarketplaceItem,
  ModerationActionType as _ModerationActionType,
  NotificationDelivery as _NotificationDelivery,
  PaymentStatus as _PaymentStatus,
  PaymentType as _PaymentType,
  PendingDecision as _PendingDecision,
  PendingDecisionEntry as _PendingDecisionEntry,
  PersonaMode as _PersonaMode,
  PickIncludedShardRequest as _PickIncludedShardRequest,
  ProvisioningType as _ProvisioningType,
  ReportStatus as _ReportStatus,
  ReportTargetType as _ReportTargetType,
  ShardDecisionRequest as _ShardDecisionRequest,
  ShardDetail as _ShardDetail,
  ShardSummary as _ShardSummary,
  ShardType as _ShardType,
  SubscriptionTier as _SubscriptionTier,
  TechnologyLevel as _TechnologyLevel,
  TierLimits as _TierLimits,
  TravelState as _TravelState,
  UserRelationshipType as _UserRelationshipType,
  WaitlistStatus as _WaitlistStatus,
} from './generated';

// Re-export for consumers
export type AccountStatus = _AccountStatus;
export type AccountType = _AccountType;
export type CancelRequest = _CancelRequest;
export type ChannelType = _ChannelType;
export type CommitRequest = _CommitRequest;
export type ConflictStyle = _ConflictStyle;
export type ConsentType = _ConsentType;
export type ConversationRole = _ConversationRole;
export type DowngradeSession = _DowngradeSession;
export type DowngradeSessionState = _DowngradeSessionState;
export type DowngradeSessionView = _DowngradeSessionView;
export type EconomicModel = _EconomicModel;
export type EchoRelationshipType = _EchoRelationshipType;
export type EchoStatus = _EchoStatus;
export type ExportFormat = _ExportFormat;
export type ExportStatus = _ExportStatus;
export type GlobalEventStatus = _GlobalEventStatus;
export type GlobalEventType = _GlobalEventType;
export type LifeEventType = _LifeEventType;
export type LocationType = _LocationType;
export type MarketplaceCategory = _MarketplaceCategory;
export type ModerationActionType = _ModerationActionType;
export type NotificationDelivery = _NotificationDelivery;
export type PaymentStatus = _PaymentStatus;
export type PaymentType = _PaymentType;
export type PendingDecision = _PendingDecision;
export type PendingDecisionEntry = _PendingDecisionEntry;
export type PersonaMode = _PersonaMode;
export type PickIncludedShardRequest = _PickIncludedShardRequest;
export type ProvisioningType = _ProvisioningType;
export type ReportStatus = _ReportStatus;
export type ReportTargetType = _ReportTargetType;
export type ShardDecisionRequest = _ShardDecisionRequest;
export type ShardType = _ShardType;
export type SubscriptionTier = _SubscriptionTier;
export type TechnologyLevel = _TechnologyLevel;
export type TierLimits = _TierLimits;
export type TravelState = _TravelState;
export type UserRelationshipType = _UserRelationshipType;
export type WaitlistStatus = _WaitlistStatus;

// --- Common ---

export interface ApiError {
  error: {
    code: string;
    message: string;
  };
}

export interface MessageResponse {
  message: string;
}

// --- Auth ---

export interface RegisterRequest {
  email: string;
  password: string;
  display_name: string;
  tos_accepted: boolean;
  privacy_accepted: boolean;
  age_confirmed: boolean;
  cf_turnstile_response?: string;
  invite_code: string;
}

export interface RegisterResponse {
  user_id: string;
  display_name: string;
  message: string;
  email_verified: boolean;
  access_token: string;
  refresh_token: string;
  expires_in: number;
}

export interface LoginRequest {
  email: string;
  password: string;
  cf_turnstile_response?: string;
}

export interface LoginResponse {
  access_token: string;
  refresh_token: string;
  expires_in: number;
  /** Server-side `[legal] current_tos_version` — the version the
   *  client must offer in `account.acceptTos(version)` if
   *  `requires_tos_reacceptance` is true. Reference: ME-ILF-001 §3.1.1. */
  current_tos_version: string;
  /** `true` when the user must re-accept the current ToS before
   *  continuing. The server does not block requests; the client gates
   *  the in-app flow on this value. Reference: ME-ILF-001 §3.1.1. */
  requires_tos_reacceptance: boolean;
}

export interface RefreshRequest {
  refresh_token: string;
}

export interface RefreshResponse {
  access_token: string;
  refresh_token: string;
  expires_in: number;
}

// --- User ---

export interface User {
  user_id: string;
  email: string;
  email_verified: boolean;
  display_name: string;
  display_name_slug: string;
  account_type: AccountType;
  subscription_tier: SubscriptionTier;
  created_at: string;
  updated_at: string;
  last_login_at: string;
  account_status: AccountStatus;
  locale: string;
  timezone: string | null;
  onboarding_complete: boolean;
  tos_accepted_at: string;
  tos_version: string;
  privacy_accepted_at: string;
  privacy_version: string;
  /** Server-side `[legal] current_tos_version` — echoed on every
   *  `/account/me` read so refresh-path sessions still know which
   *  version to submit when accepting. Reference: ME-ILF-001 §3.1.1. */
  current_tos_version: string;
  /** `true` when User.tos_version differs from `[legal] current_tos_version`
   *  AND the 30-day notice window has elapsed. The client renders a
   *  re-acceptance modal/banner when this is true and calls
   *  `account.acceptTos(currentTosVersion)`. The server does not block
   *  requests on a stale version — gating is presentation-layer only.
   *  Reference: ME-ILF-001 §3.1.1, ME-UAD-001 §2.2. */
  requires_tos_reacceptance: boolean;
  echo_count_limit: number;
  solo_mode: boolean;
  deletion_scheduled_at: string | null;
  do_not_sell: boolean;
  analytics_opt_out: boolean;
  subscription_expires_at: string | null;
}

// --- Echo ---

export interface CreateEchoRequest {
  name: string;
  persona_text: string;
  what_if_prompt: string;
  age_at_creation?: number;
  persona_mode?: 'detailed' | 'quick';
  consent_declaration: boolean;
  persona_declaration?: 'inspired' | 'fictional';
  shard_id?: string;
  /** Optional free-text description. When set, used directly as the FLUX.2
   *  portrait prompt and the LLM bio-extraction step is skipped. Max 1000. */
  physical_description?: string;
}

/** Server-sourced Echo response. Regenerated from the Rust struct via
 *  `cargo run --bin generate-types`; this file re-exports the specta
 *  shape rather than redeclaring fields, so new server-added fields
 *  (e.g. `hibernated_at`, `persona_text_original`) flow through without
 *  a hand-maintained duplicate. */
export type EchoResponse = _EchoResponse;

// --- Shard ---

export type ShardSummary = _ShardSummary;
export type ShardDetail = _ShardDetail;

/** Alias for backward compatibility — maps to ShardSummary. */
export type Shard = ShardSummary;

// --- Diary ---

export interface DiaryEntry {
  diary_id: string;
  echo_id: string;
  tick_id: number;
  simulated_date: string;
  content: string;
  mood: string;
  location_name: string;
  shard_id: string;
  nudge_source?: string | null;
  image_url?: string | null;
  created_at: string;
}

// --- Feed ---

export interface FeedItem {
  item_id: string;
  item_type: string;
  echo_id: string;
  shard_id: string;
  title: string;
  body: string;
  significance: number;
  tick_id: number;
  created_at: string;
  is_public: boolean;
}

// --- Notification ---

export interface Notification {
  notification_id: string;
  user_id: string;
  category: string;
  title: string;
  body: string;
  read: boolean;
  created_at: string;
}

// --- Relationship ---

export interface EchoRelationship {
  relationship_id: string;
  echo_a_id: string;
  echo_b_id: string;
  other_echo_name?: string;
  other_echo_owner_name?: string;
  relationship_type: string;
  status: string;
  formed_at_tick: number;
  last_interaction_tick: number;
  sentiment: number;
  key_moments: string[];
  is_cross_user: boolean;
  cross_user_consent: boolean;
  created_at: string;
  updated_at: string;
}

// --- Influence ---

export interface InfluenceBalance {
  echo_id: string;
  /** `null` when the tier is uncapped (GodMode), `number` for finite caps. */
  daily_limit: number | null;
  /** `null` when daily_limit is null; `number` otherwise. */
  used_today: number | null;
  /** `null` when daily_limit is null; `number` otherwise. */
  remaining: number | null;
}

export interface UseInfluenceRequest {
  influence_type: string;
  suggestion: string;
}

// --- Memory ---

export interface EchoMemory {
  memory_id: string;
  echo_id: string;
  source_tick_id: number;
  memory_type: string;
  content: string;
  emotional_valence: number;
  importance: number;
  embedding_id: string;
  is_summarised: boolean;
  summarised_from: string[];
  created_at: string;
  last_accessed_tick: number;
}

// --- Channel ---

export interface Channel {
  channel_id: string;
  name: string;
  channel_type: ChannelType;
  scope_id: string | null;
  status: string;
  description: string;
  is_read_only: boolean;
  slow_mode_seconds: number;
  created_at: string;
}

export interface ChannelMessage {
  message_id: string;
  channel_id: string;
  author_id: string;
  author_display_name: string;
  content: string;
  message_type: string;
  created_at: string;
  edited_at: string | null;
  is_edited: boolean;
  can_edit: boolean;
  can_delete: boolean;
  image_url: string | null;
  poll_data: string | null;
}

export interface PollData {
  question: string;
  options: PollOption[];
  discord_message_id: string;
  discord_channel_id: string;
}

export interface PollOption {
  id: number;
  text: string;
  votes: number;
}

export interface SendMessageRequest {
  content: string;
}

export interface EditMessageRequest {
  content: string;
}

// --- Account Settings ---

export interface ChangePasswordRequest {
  current_password: string;
  new_password: string;
}

export interface NotificationPreferences {
  user_id: string;
  echo_life_events: NotificationDelivery;
  daily_digest: NotificationDelivery;
  social: NotificationDelivery;
  community: NotificationDelivery;
  shard_activity: NotificationDelivery;
  platform: NotificationDelivery;
  marketplace: NotificationDelivery;
  billing: NotificationDelivery;
  moderation: NotificationDelivery;
  account: NotificationDelivery;
  quiet_hours_start: string | null;
  quiet_hours_end: string | null;
  updated_at: string;
}

// --- API Keys ---

export interface ApiKey {
  key_id: string;
  name: string;
  key_prefix: string;
  created_at: string;
}

export interface CreateApiKeyRequest {
  name: string;
}

export interface CreateApiKeyResponse {
  key_id: string;
  key: string;
  name: string;
  created_at: string;
}

// --- Admin ---

export interface SystemHealth {
  tick_number: number;
  tick_duration_ms: number;
  ram_usage_mb: number;
  vram_usage_mb: number;
  vram_total_mb: number;
  active_echoes: number;
  hibernated_echoes: number;
  total_users: number;
  total_shards: number;
}

export interface AdminReport {
  report_id: string;
  reporter_user_id: string;
  target_type: string;
  target_id: string;
  reason: string;
  details: string;
  priority: string;
  status: string;
  sla_deadline: string;
  created_at: string;
}

export interface AdminUser {
  user_id: string;
  email: string;
  display_name: string;
  account_type: AccountType;
  subscription_tier: SubscriptionTier;
  account_status: AccountStatus;
  echo_count: number;
  created_at: string;
  last_login_at: string;
}

export interface ResolveReportRequest {
  action: 'Quarantine' | 'Warn' | 'Suspend' | 'Dismiss' | 'Restore';
  notes: string;
}

export interface ModeratorUserItem {
  user_id: string;
  email: string;
  display_name: string;
  account_type: AccountType;
  updated_at: string;
}

// --- Feedback ---

export type FeedbackType =
  | 'Bug'
  | 'FeatureRequest'
  | 'Frustration'
  | 'Praise'
  | 'General';
export type FeedbackStatus = 'New' | 'Acknowledged' | 'Resolved' | 'Wontfix';
export type FeedbackPriority = 'P0' | 'P1' | 'P2' | 'P3' | 'P4';

export interface FeedbackContext {
  screen: string;
  echo_id?: string | null;
  shard_id?: string | null;
  recent_events: string[];
}

export interface FeedbackEntry {
  feedback_id: string;
  user_id: string;
  feedback_type: FeedbackType;
  user_message: string;
  structured_summary: string;
  context: FeedbackContext;
  status: FeedbackStatus;
  priority?: FeedbackPriority | null;
  github_issue_url?: string | null;
  resolution_notes?: string | null;
  created_at: string;
  updated_at: string;
}

export interface SubmitFeedbackRequest {
  user_message: string;
  structured_summary: string;
  feedback_type: FeedbackType;
  context: FeedbackContext;
}

export interface SubmitFeedbackResponse {
  feedback_id: string;
  status: string;
  message: string;
}

// --- Data Export ---

export interface DataExport {
  export_id: string;
  status: ExportStatus;
  format: ExportFormat;
  download_url?: string;
  download_path?: string;
  subtitle_path?: string;
  created_at: string;
}

export interface RequestExportBody {
  echo_ids: string[];
  format: ExportFormat;
  from_date?: string;
  to_date?: string;
}

// --- Conversation ---

export interface Conversation {
  conversation_id: string;
  echo_id: string;
  created_at: string;
  saved: boolean;
}

export interface ConversationMessage {
  message_id: string;
  conversation_id: string;
  role: 'user' | 'echo';
  content: string;
  created_at: string;
}

export interface CreateConversationResponse {
  conversation_id: string;
  echo_id: string;
  created_at: string;
  saved: boolean;
}

export interface ActiveConversationResponse {
  conversation_id: string;
  echo_id: string;
  created_at: string;
  saved: boolean;
  resumed: boolean;
  messages: ConversationMessage[];
}

export interface SendConversationMessageRequest {
  content: string;
}

// --- Search ---

export interface SearchResult {
  id: string;
  result_type: 'Echo' | 'DiaryEntry' | 'LifeEvent' | 'Shard' | 'Message';
  title: string;
  snippet: string;
  echo_id?: string;
  shard_id?: string;
  created_at: string;
}

export interface SearchParams {
  q: string;
  echo_id?: string;
  shard_id?: string;
  content_type?: string;
  date_from?: string;
  date_to?: string;
}

// --- Oracle ---

export interface OracleAskRequest {
  question: string;
  context?: OracleContext;
  history?: Array<{ role: string; text: string }>;
}

export interface OracleContext {
  echo_id?: string;
  shard_id?: string;
  screen?: string;
}

export interface OracleResponse {
  answer: string;
  deep_links?: OracleDeepLink[];
}

export interface OracleDeepLink {
  label: string;
  path: string;
}

// --- Waitlist ---

export interface WaitlistSignupRequest {
  email: string;
  referral_code?: string;
  source?: string;
}

export interface WaitlistSignupResponse {
  entry_id: string;
  position: number;
  referral_code: string;
}

export interface WaitlistPositionResponse {
  entry_id: string;
  position: number;
  status: string;
  referral_code: string;
  referral_count: number;
}

export interface WaitlistCountResponse {
  count: number;
}

// --- Life Event ---

export interface LifeEvent {
  event_id: string;
  echo_id: string;
  tick_id: number;
  event_type: LifeEventType;
  headline: string;
  narrative: string;
  significance_score: number;
  location_name: string;
  shard_id: string;
  related_echo_ids: string[];
  content_hash: string;
  created_at: string;
}

// --- Marketplace ---

// Re-exported from `generated.ts` (Specta from
// `me_core::models::marketplace::MarketplaceItem`). The Lane E
// Commit 2.5 schema rationalization deleted the
// `me_core::models::community::MarketplaceItem` orphan that had
// previously shaped this re-export — the hand-written interface
// that lived here mirrored the orphan (price_cents,
// preview_asset, content_hash, available_from) and never matched
// any real wire shape. Consumers should prefer
// `MarketplaceItemResponse` (also from `generated.ts`) for
// rendering server payloads.
export type MarketplaceItem = _MarketplaceItem;

// --- User Relationship ---

export interface UserRelationship {
  relationship_id: string;
  source_user_id: string;
  target_user_id: string;
  relationship_type: UserRelationshipType;
  created_at: string;
}

// --- Shard Theme ---

export interface ShardTheme {
  theme_id: string;
  shard_id: string;
  setting_prompt: string;
  cultural_norms: string;
  economic_model: EconomicModel;
  technology_level: TechnologyLevel;
  conflict_style: ConflictStyle;
  available_occupations: string[];
  banned_elements: string[];
  custom_rules: string;
  shard_prompt_template: string | null;
  visual_style: string | null;
  starting_wealth: number;
}

// --- Shard Location ---

export interface ShardLocation {
  location_id: string;
  shard_id: string;
  name: string;
  location_type: LocationType;
  description: string;
  capacity: number;
  connects_to: string[];
  travel_time_ticks: number;
  is_spawn_point: boolean;
  social_density: number;
  economic_activity: number;
  danger_level: number;
}

// --- Shard Placement ---

export interface ShardPlacement {
  echo_id: string;
  shard_id: string;
  location_id: string;
  arrived_at_tick: number;
  travel_state: TravelState;
  destination_id: string | null;
  arrival_tick: number | null;
}

// --- Global Event ---

export interface GlobalEvent {
  event_id: string;
  name: string;
  description: string;
  event_type: GlobalEventType;
  intensity: number;
  affected_shards: string[];
  start_tick: number;
  duration_ticks: number;
  status: GlobalEventStatus;
  created_at: string;
}

// --- Content Flag ---

export type ContentTier = 'T0' | 'T1' | 'T2' | 'T3'; // Client-specific — Rust uses ContentTierEnum

export interface ContentFlag {
  flag_id: string;
  tick_id: number;
  echo_id: string;
  tier: ContentTier;
  raw_content_hash: string;
  classification_reason: string;
  action_taken: string;
  reviewed_by: string | null;
  review_timestamp: string | null;
}

// --- User Report ---

export interface UserReport {
  report_id: string;
  reporter_user_id: string;
  target_type: ReportTargetType;
  target_id: string;
  reason: string;
  details: string;
  status: ReportStatus;
  priority: number;
  created_at: string;
  resolved_at: string | null;
  resolution: string | null;
}

// --- Moderation Action ---

export interface ModerationAction {
  action_id: string;
  moderator_id: string;
  target_user_id: string | null;
  target_message_id: string | null;
  target_channel_id: string | null;
  action_type: ModerationActionType;
  reason: string;
  duration_seconds: number | null;
  created_at: string;
  expires_at: string | null;
}

// --- Consent Record ---

export interface ConsentRecord {
  consent_id: string;
  user_id: string;
  consent_type: ConsentType;
  version: string;
  granted_at: string;
  withdrawn_at: string | null;
  ip_hash: string;
  context: string;
}

// --- Payment Record ---

export interface PaymentRecord {
  payment_id: string;
  user_id: string;
  payment_type: PaymentType;
  provider: string;
  provider_payment_id: string;
  amount_usd_cents: number;
  currency: string;
  crypto_amount?: string | null;
  status: PaymentStatus;
  description: string;
  created_at: string;
  confirmed_at: string | null;
}

// --- WebSocket Events ---

/** Envelope for full WorldEvents (used by shard/channel streams). */
export interface WorldEvent {
  event_id: string;
  tick_id: number;
  timestamp: string;
  payload: WorldEventPayload;
}

export type WorldEventPayload =
  | { type: 'DiaryEntryGenerated'; echo_id: string; diary_id: string }
  | { type: 'LifeEventOccurred'; echo_id: string; event_id: string }
  | { type: 'MoodChanged'; echo_id: string; old_mood: string; new_mood: string }
  | {
      type: 'EchoInteraction';
      echo_a: string;
      echo_b: string;
      interaction_type: string;
      tick_id: number;
    }
  | { type: 'EchoHibernated'; echo_id: string; reason: string }
  | { type: 'EchoWoken'; echo_id: string }
  | { type: 'EchoCreated'; echo_id: string; owner_id: string }
  | { type: 'EchoDeleted'; echo_id: string }
  | {
      type: 'EchoMoved';
      echo_id: string;
      shard_id: string;
      from_location: string;
      to_location: string;
      arrival_tick: number;
    }
  | {
      type: 'EchoWealthChanged';
      echo_id: string;
      old_value: number;
      new_value: number;
      reason: string;
    }
  | { type: 'RelationshipFormed'; echo_a: string; echo_b: string }
  | { type: 'ShardTravelCompleted'; echo_id: string; shard_id: string }
  | {
      type: 'ShardCreated';
      shard_id: string;
      shard_type: string;
      owner_id: string;
    }
  | {
      type: 'ShardStatusChanged';
      shard_id: string;
      old_status: string;
      new_status: string;
    }
  | {
      type: 'GlobalEventPropagated';
      event_id: string;
      affected_shards: string[];
    }
  | { type: 'PersonaUpdated'; echo_id: string; version: number }
  | {
      type: 'CommunityMessagePosted';
      channel_id: string;
      message_id: string;
      author_id: string;
    }
  | {
      type: 'MessageDeleted';
      channel_id: string;
      message_id: string;
      deleted_by: string;
    }
  | {
      type: 'MessageEdited';
      channel_id: string;
      message_id: string;
      author_id: string;
    }
  | {
      type: 'FeedItemGenerated';
      feed_item_id: string;
      echo_id: string;
      shard_id: string;
    }
  | { type: 'NotificationCreated'; user_id: string; notification_id: string }
  | { type: string; [key: string]: unknown };

/** Flat tagged events sent over Echo/Dashboard WS streams (server's WsEchoEvent). */
export type WsEchoEvent =
  | {
      type: 'DiaryEntryCreated';
      echo_id: string;
      diary_id: string;
      tick_id: number;
    }
  | {
      type: 'DiaryImageReady';
      echo_id: string;
      diary_id: string;
      image_url: string;
    }
  | {
      type: 'LifeEventOccurred';
      echo_id: string;
      event_id: string;
      tick_id: number;
    }
  | { type: 'MoodChanged'; echo_id: string; mood: string; tick_id: number }
  | {
      type: 'EchoMoved';
      echo_id: string;
      from_location: string;
      to_location: string;
    }
  | { type: 'PersonaUpdated'; echo_id: string; version: number }
  | { type: 'EchoHibernated'; echo_id: string; reason: string }
  | { type: 'EchoWoken'; echo_id: string }
  | {
      type: 'EchoWealthChanged';
      echo_id: string;
      old_value: number;
      new_value: number;
      reason: string;
    }
  | { type: 'EchoDeleted'; echo_id: string }
  | { type: 'ShardTravelCompleted'; echo_id: string; shard_id: string }
  | { type: 'EchoAvatarReady'; echo_id: string; avatar_url: string }
  | { type: 'ShardCreated'; shard_id: string; shard_type: string }
  | {
      type: 'CommunityMessagePosted';
      channel_id: string;
      message_id: string;
      author_id: string;
    }
  | {
      type: 'CommunityMessageEdited';
      channel_id: string;
      message_id: string;
      author_id: string;
    }
  | {
      type: 'CommunityMessageDeleted';
      channel_id: string;
      message_id: string;
      deleted_by: string;
    }
  | { type: 'NotificationCreated'; notification_id: string }
  | {
      type: 'PaymentFailed';
      provider: _CryptoBillingProvider;
      attempt_number: number;
    }
  | {
      type: 'DunningPhaseChanged';
      provider: _CryptoBillingProvider;
      from: _DunningPhase;
      to: _DunningPhase;
    }
  // Lane H Commit 7: admin-dashboard-only revocation broadcast.
  // Server filters to admin sockets via the dashboard handler arm.
  | {
      type: 'ShareTokenRevoked';
      token: string;
      revoked_by_user_id: string | null;
      reason: string;
    }
  | { type: 'Connected'; echo_id?: string; message: string }
  | { type: 'Error'; message: string }
  | { type: string; [key: string]: unknown };
