// This file is auto-generated by `cargo run --bin generate-types`.
// Do not edit manually. Changes will be overwritten.
// Source: crates/shared/src/bin/generate_types.rs
// This file has been generated by Specta. Do not edit this file manually.
export type AccountStatus = "Active" | "Suspended" | "PendingDeletion" | "Deleted";

export type AccountType = "Standard" | "Admin";

export type ActiveConversationResponse = {
	conversation_id: string,
	echo_id: string,
	created_at: string,
	saved: boolean,
	// Whether this conversation was resumed (true) or newly created (false).
	resumed: boolean,
	// Preloaded messages if this was a resumed conversation.
	messages: ConversationMessageResponse[],
};

// A single analytics event.
export type AnalyticsEvent = {
	id: string,
	user_id: string,
	event_name: string,
	created_at: string,
	source: EventSource,
};

/**
 *  Aggregated daily summary for retention sweep.
 *  Reference: ME-PDP-001 §5.1, Task E1.
 */
export type AnalyticsSummary = {
	id: string,
	date: string,
	event_name: string,
	count: number,
	distinct_users: number,
};

// API key for third-party access. Reference: ME-API-001 §3.2.
export type ApiKey = {
	key_id: string,
	user_id: string,
	name: string,
	// Last 4 characters of the key for display.
	key_prefix: string,
	created_at: string,
	revoked_at: string | null,
};

export type ApiKeyListItem = {
	key_id: string,
	name: string,
	// Last 4 chars of the key.
	key_prefix: string,
	created_at: string,
};

/**
 *  Beta invite code for gated registration.
 *  Reference: ME-UXF-001 §4.2.
 */
export type BetaInvite = {
	id: string,
	code: string,
	// Email address the invite was issued to (for auto-claim on registration).
	email?: string | null,
	created_by: string,
	claimed_by: string | null,
	claimed_at: string | null,
	expires_at: string,
	created_at: string,
};

/**
 *  GDPR Article 33 breach record-keeping.
 *  Reference: ME-PDP-001 §6.2.
 */
export type BreachRecord = {
	id: string,
	detected_at: string,
	severity: BreachSeverity,
	description: string,
	affected_user_count: number,
	response_actions: string[],
	notified_authorities: boolean,
	notified_users: boolean,
	resolved_at: string | null,
	created_by: string,
};

/**
 *  Severity level for GDPR breach records.
 *  Reference: ME-PDP-001 §6.2.
 */
export type BreachSeverity = "Low" | "Medium" | "High" | "Critical";

export type Channel = {
	channel_id: string,
	name: string,
	channel_type: ChannelType,
	scope_id: string | null,
	created_at: string,
	status: ChannelStatus,
	description: string,
	is_read_only: boolean,
	slow_mode_seconds: number,
};

export type ChannelMessage = {
	message_id: string,
	channel_id: string,
	author_id: string,
	content: string,
	message_type: MessageType,
	reply_to: string | null,
	created_at: string,
	edited_at: string | null,
	is_deleted: boolean,
	attached_echo_id: string | null,
	attached_export_id: string | null,
	// Discord CDN URL for image attachments.
	image_url?: string | null,
	// JSON-serialized poll data (question, options, votes).
	poll_data?: string | null,
};

export type ChannelResponse = {
	channel_id: string,
	name: string,
	channel_type: ChannelType,
	scope_id: string | null,
	status: ChannelStatus,
	description: string,
	is_read_only: boolean,
	slow_mode_seconds: number,
	created_at: string,
};

export type ChannelStatus = "Active" | "Archived" | "Locked";

export type ChannelType = "Shard" | "Global" | "Topic" | "PrivateShard" | "Event";

export type ConflictStyle = "Peaceful" | "Political" | "Economic" | "Military" | "Survival";

export type ConsentRecord = {
	consent_id: string,
	user_id: string,
	consent_type: ConsentType,
	version: string,
	granted_at: string,
	withdrawn_at: string | null,
	ip_hash: string,
	context: string,
};

export type ConsentType = "ToS" | "Privacy" | "PersonaData" | "CrossUserInteraction" | "Community";

export type ContentFlag = {
	flag_id: string,
	tick_id: number,
	echo_id: string,
	tier: ContentTierEnum,
	raw_content_hash: string,
	classification_reason: string,
	action_taken: string,
	reviewed_by: string | null,
	review_timestamp: string | null,
};

export type ContentTierEnum = "T0" | "T1" | "T2" | "T3";

// Direct conversation between a user and their Echo. Reference: ME-UXF-001 §7.7.
export type Conversation = {
	conversation_id: string,
	echo_id: string,
	user_id: string,
	created_at: string,
	saved: boolean,
};

// A message in a direct Echo conversation.
export type ConversationMessage = {
	message_id: string,
	conversation_id: string,
	role: ConversationRole,
	content: string,
	created_at: string,
};

export type ConversationMessageResponse = {
	message_id: string,
	role: string,
	content: string,
	created_at: string,
};

export type ConversationResponse = {
	conversation_id: string,
	echo_id: string,
	created_at: string,
	saved: boolean,
};

// Role in a direct Echo conversation.
export type ConversationRole = "User" | "Echo";

export type CreateApiKeyRequest = {
	name: string,
};

export type CreateApiKeyResponse = {
	key_id: string,
	name: string,
	// The raw API key — shown once, never again.
	key: string,
	created_at: string,
};

export type CreateChannelRequest = {
	name: string,
	description: string | null,
	channel_type: ChannelType,
	is_read_only: boolean | null,
	slow_mode_seconds: number | null,
};

// POST /echoes — Create a new Echo.
export type CreateEchoRequest = {
	name: string,
	persona_text: string,
	what_if_prompt: string,
	age_at_creation?: number | null,
	persona_mode?: string | null,
	consent_declaration: boolean,
	// Optional: create Echo in a specific Public Shard instead of Personal Shard.
	shard_id?: string | null,
	/**
	 *  Optional free-text physical description. When present and non-empty,
	 *  it is used directly as the FLUX.2 portrait prompt and the LLM
	 *  descriptor extraction from `persona_text` is skipped.
	 */
	physical_description?: string | null,
};

export type CreateReportRequest = {
	target_type: string,
	target_id: string,
	reason: string,
	details: string | null,
};

export type DataAccessLog = {
	log_id: string,
	accessor_id: string,
	target_id: string | null,
	access_type: DataAccessType,
	resource: string,
	reason: string,
	timestamp: string,
};

export type DataAccessType = "Read" | "Export" | "Modify" | "Delete" | "AdminView";

// Data export request (Right of Access). Reference: ME-PDP-001 §4.
export type DataExport = {
	export_id: string,
	user_id: string,
	status: ExportStatus,
	created_at: string,
	completed_at: string | null,
	download_path: string | null,
};

/**
 *  Permanent ledger of deleted user IDs.
 *  Used for backup restoration — re-purge deleted users after restore.
 *  Reference: ME-PDP-001 §5.3.
 */
export type DeletionLedger = {
	id: string,
	// SHA-256 hash of the user_id, NOT the raw UUID.
	user_id_hash: string,
	deleted_at: string,
};

export type DetailedHealthResponse = {
	status: string,
	tick_rate_seconds: number,
	active_echo_count: number,
	memory_usage_mb: number,
	vram_usage_mb: number,
	version: string,
};

export type DiaryEntry = {
	diary_id: string,
	echo_id: string,
	tick_id: number,
	simulated_date: string,
	content: string,
	mood: string,
	location_name: string,
	shard_id: string,
	word_count: number,
	content_hash: string,
	// If this diary entry was influenced by a user nudge, the nudge text.
	nudge_source?: string | null,
	// URL of the generated scene image for this diary entry.
	image_url?: string | null,
	created_at: string,
};

// Discord account link. Reference: ME-CSS-001 §4.
export type DiscordLink = {
	user_id: string,
	discord_user_id: string,
	discord_username: string,
	linked_at: string,
	sync_display_name: boolean,
	// Discord OAuth access token (stored encrypted at rest in production).
	access_token?: string | null,
	// Discord OAuth refresh token (stored encrypted at rest in production).
	refresh_token?: string | null,
};

export type Echo = {
	echo_id: string,
	owner_user_id: string,
	name: string,
	persona_text: string,
	what_if_prompt: string,
	persona_version: number,
	persona_mode: PersonaMode,
	status: EchoStatus,
	age_at_creation: number,
	current_mood: string,
	current_tick: number,
	// Global tick_id when this Echo was first processed. Used for per-Echo relative time.
	birth_tick_id?: number,
	current_shard_id: string,
	current_location_id: string,
	memory_token_count: number,
	last_summarised_at: number,
	relationship_count: number,
	/**
	 *  Echo's current wealth in the Shard's economy (fixed-point).
	 *  Resets to destination Shard's starting_wealth on inter-Shard travel.
	 */
	wealth?: number,
	consent_declaration: boolean,
	consent_timestamp: string,
	birth_hash: string,
	created_at: string,
	updated_at: string,
	hibernated_at: string | null,
	deleted_at: string | null,
	/**
	 *  URL of the AI-generated portrait image (face, generated once at creation from bio).
	 *  Used as the MuseTalk reference face for voice sessions.
	 */
	avatar_url?: string | null,
	/**
	 *  Optional free-text physical description supplied at Echo creation.
	 *  When present and non-empty, this is used DIRECTLY as the FLUX.2
	 *  portrait prompt (with the shard's `visual_style` appended), bypassing
	 *  the LLM extraction step from `persona_text`. Introduced 2026-04-05.
	 *  Older Echoes deserialise with `None` via `#[serde(default)]`.
	 */
	physical_description?: string | null,
};

export type EchoMemory = {
	memory_id: string,
	echo_id: string,
	source_tick_id: number,
	memory_type: MemoryType,
	content: string,
	emotional_valence: number,
	importance: number,
	embedding_id: string,
	is_summarised: boolean,
	summarised_from: string[],
	created_at: string,
	last_accessed_tick: number,
};

export type EchoRelationship = {
	relationship_id: string,
	echo_a_id: string,
	echo_b_id: string,
	relationship_type: EchoRelationshipType,
	status: RelationshipStatus,
	formed_at_tick: number,
	last_interaction_tick: number,
	sentiment: number,
	key_moments: string[],
	is_cross_user: boolean,
	cross_user_consent: boolean,
	created_at: string,
	updated_at: string,
};

export type EchoRelationshipType = "Friend" | "Rival" | "RomanticPartner" | "Colleague" | "Acquaintance" | "Family" | "Mentor" | "Adversary";

export type EchoResponse = {
	echo_id: string,
	name: string,
	persona_text: string,
	what_if_prompt: string,
	persona_version: number,
	status: string,
	current_mood: string,
	current_tick: number,
	current_shard_id: string,
	birth_hash: string,
	created_at: string,
	// True if the Echo has ticked at least once — name cannot be changed.
	name_locked: boolean,
	// URL of the AI-generated portrait image (face). Null if generation failed or pending.
	avatar_url: string | null,
	/**
	 *  Free-text physical description supplied at creation (optional).
	 *  Null for Echoes created before the field was introduced.
	 */
	physical_description: string | null,
};

export type EchoStatus = "Active" | "Travelling" | "Hibernated" | "Quarantined" | "Deleted";

export type EconomicModel = "Capitalist" | "Socialist" | "Barter" | "PostScarcity" | "Feudal" | "Custom";

export type EditMessageRequest = {
	content: string,
};

export type EnforcementAction = {
	action_id: string,
	user_id: string | null,
	action_type: EnforcementActionType,
	reason: string,
	created_at: string,
	expires_at: string | null,
};

export type EnforcementActionType = "MessageDeleted" | "UserMuted" | "UserChannelBanned" | "ChannelLocked" | "Warning" | "Quarantine" | "Suspension" | "Ban" | "FalsePositiveRestoration";

// Source of an analytics event.
export type EventSource = "Client" | "Engine";

// Format for story export. Reference: ME-UAD-001 §5.4.
export type ExportFormat = "text" | "json" | "pdf" | "video" | "book";

export type ExportResponse = {
	export_id: string,
	status: string,
	created_at: string,
	download_path: string | null,
};

// Status of a data export request.
export type ExportStatus = "Processing" | "Complete" | "Failed";

export type FeedItem = {
	item_id: string,
	item_type: FeedItemType,
	echo_id: string,
	shard_id: string,
	owner_user_id: string,
	headline: string,
	body: string,
	significance_score: number,
	tick_id: number,
	created_at: string,
	is_public: boolean,
};

export type FeedItemResponse = {
	item_id: string,
	item_type: FeedItemType,
	echo_id: string,
	shard_id: string,
	// Serialised as "title" to match client FeedItem type.
	title: string,
	body: string,
	// Serialised as "significance" to match client FeedItem type.
	significance: number,
	tick_id: number,
	created_at: string,
	is_public: boolean,
};

export type FeedItemType = "diary_entry" | "life_event" | "relationship_change" | "achievement" | "global_event_participation" | "user_shared";

/**
 *  A global event that affects one or more Shards.
 *  Reference: ME-SDB-001 §7.1.
 */
export type GlobalEvent = {
	event_id: string,
	name: string,
	description: string,
	event_type: GlobalEventType,
	// Intensity: fixed-point 0–1000 (0.0–1.0).
	intensity: number,
	// Affected shard IDs. Empty = all active Shards.
	affected_shards: string[],
	start_tick: number,
	duration_ticks: number,
	status: GlobalEventStatus,
	created_at: string,
};

// Lifecycle status of a global event.
export type GlobalEventStatus = "Scheduled" | "Active" | "Completed";

/**
 *  Types of global events that affect Shards.
 *  Reference: ME-SDB-001 §7.1.
 */
export type GlobalEventType = "Economic" | "Social" | "Environmental" | "Political" | "Cultural";

export type HealthResponse = {
	status: string,
	tick_interval_seconds: number,
	// Epoch milliseconds when the last tick completed. 0 if no tick has run yet.
	last_tick_at: number,
};

// POST /echoes/:id/influence — Apply influence to an Echo.
export type InfluenceRequest = {
	suggestion: string,
	influence_type: string,
};

export type InfluenceResponse = {
	influence_id: string,
	remaining_points: number,
};

export type LifeEvent = {
	event_id: string,
	echo_id: string,
	tick_id: number,
	event_type: LifeEventType,
	headline: string,
	narrative: string,
	significance_score: number,
	location_name: string,
	shard_id: string,
	related_echo_ids: string[],
	content_hash: string,
	created_at: string,
};

export type LifeEventType = "Career" | "Relationship" | "Personal" | "Conflict" | "Achievement" | "Travel" | "Health" | "Financial" | "Social" | "GlobalEvent";

export type LocationType = "Residential" | "Commercial" | "Social" | "Workplace" | "Transit" | "Landmark" | "Wilderness";

export type MarketplaceCategory = "DashboardTheme" | "PortraitStyle" | "ExportTemplate" | "ShardAesthetic" | "ScenarioPack" | "SeasonalCosmetic" | "SoundPack";

export type MarketplaceItem = {
	item_id: string,
	name: string,
	description: string,
	category: MarketplaceCategory,
	price_cents: number,
	is_available: boolean,
	is_limited_time: boolean,
	available_from: string | null,
	available_until: string | null,
	preview_asset: string,
	creator_id: string | null,
	content_hash: string,
	created_at: string,
};

export type MemoryType = "Episodic" | "Semantic" | "Emotional" | "Relationship" | "Summarised";

export type MessageResponse = {
	message_id: string,
	channel_id: string,
	author_id: string,
	author_display_name: string,
	content: string,
	message_type: MessageType,
	created_at: string,
	edited_at: string | null,
	is_edited: boolean,
	can_edit: boolean,
	can_delete: boolean,
	image_url: string | null,
	poll_data: string | null,
};

export type MessageType = "UserMessage" | "SystemMessage" | "EchoHighlight";

/**
 *  A moderation action taken by an admin in a channel.
 *  Reference: ME-CSS-001 §9.2.
 */
export type ModerationAction = {
	action_id: string,
	moderator_id: string,
	target_user_id: string | null,
	target_message_id: string | null,
	target_channel_id: string | null,
	action_type: ModerationActionType,
	reason: string,
	// Duration in seconds (for timed mutes). None = permanent.
	duration_seconds: number | null,
	created_at: string,
	expires_at: string | null,
};

/**
 *  Types of moderation actions in the community system.
 *  Reference: ME-CSS-001 §9.2.
 */
export type ModerationActionType = 
// Mute a user in a specific channel (timed).
"ChannelMute" | 
// Ban a user from a specific channel (permanent until removed).
"ChannelBan" | 
// Delete a message globally.
"MessageDelete" | 
// Lock a channel (no new messages).
"ChannelLock";

export type Notification = {
	notification_id: string,
	user_id: string,
	category: NotificationCategory,
	title: string,
	body: string,
	link: string,
	read: boolean,
	created_at: string,
};

export type NotificationCategory = "EchoLifeEvent" | "DailyDigest" | "Social" | "Community" | "ShardActivity" | "Platform" | "Marketplace" | "Billing" | "Moderation" | "Account";

export type NotificationDelivery = "Off" | "InApp" | "InAppAndEmail";

export type NotificationPreferences = {
	user_id: string,
	echo_life_events: NotificationDelivery,
	daily_digest: NotificationDelivery,
	social: NotificationDelivery,
	community: NotificationDelivery,
	shard_activity: NotificationDelivery,
	platform: NotificationDelivery,
	marketplace: NotificationDelivery,
	billing: NotificationDelivery,
	moderation: NotificationDelivery,
	account: NotificationDelivery,
	quiet_hours_start: string | null,
	quiet_hours_end: string | null,
	updated_at: string,
};

export type OracleAskRequest = {
	question: string,
	// Legacy field names (from server-side callers).
	context_type: string | null,
	context_id: string | null,
	// Client sends context as a nested object.
	context: OracleContextPayload | null,
	// Conversation history for session continuity (last N exchanges).
	history?: OracleHistoryMessage[],
};

export type OracleAskResponse = {
	answer: string,
	context_type: string | null,
	context_id: string | null,
};

export type OracleContextPayload = {
	echo_id: string | null,
	shard_id: string | null,
	screen: string | null,
};

// A prior message in the Oracle conversation for session continuity.
export type OracleHistoryMessage = {
	role: string,
	text: string,
};

export type PaymentRecord = {
	payment_id: string,
	user_id: string,
	payment_type: PaymentType,
	// Provider name: "nowpayments", "xaman", "stripe".
	provider: string,
	// Provider's reference ID for this payment.
	provider_payment_id: string,
	amount_usd_cents: number,
	// What the user actually paid in (e.g., "BTC", "XRP", "USD").
	currency: string,
	// Actual crypto amount paid (string to avoid float).
	crypto_amount?: string | null,
	status: PaymentStatus,
	description: string,
	created_at: string,
	confirmed_at: string | null,
};

export type PaymentStatus = "Pending" | "Confirming" | "Confirmed" | "Finished" | "Failed" | "Refunded" | "Expired";

export type PaymentType = "Subscription" | "MarketplacePurchase" | "Tip";

export type PersonaConsent = {
	consent_id: string,
	user_id: string,
	echo_id: string,
	consent_declaration: boolean,
	declaration_timestamp: string,
	is_self: boolean,
};

export type PersonaMode = "Quick" | "Detailed";

export type PostMessageRequest = {
	content: string,
};

export type ProfileVisibility = "Public" | "FriendsOnly" | "Private";

export type RelationshipStatus = "Active" | "Faded" | "Ended" | "Severed";

// PATCH /echoes/:id — Rename an Echo.
export type RenameEchoRequest = {
	name: string,
};

export type ReportResponse = {
	report_id: string,
	reporter_user_id: string,
	target_type: ReportTargetType,
	target_id: string,
	reason: string,
	details: string,
	status: ReportStatus,
	priority: number,
	created_at: string,
	resolved_at: string | null,
	resolution: string | null,
};

export type ReportStatus = "Pending" | "Reviewing" | "Resolved" | "Dismissed";

export type ReportTargetType = "Echo" | "User" | "Content" | "Message";

export type SearchResult = {
	item_type: string,
	item_id: string,
	echo_id: string | null,
	snippet: string,
	created_at: string,
};

export type SendMessageRequest = {
	content: string,
};

export type Shard = {
	shard_id: string,
	name: string,
	name_slug: string,
	shard_type: ShardType,
	owner_id: string | null,
	created_at: string,
	status: ShardStatus,
	tick_rate_modifier: number,
	max_active_echoes: number,
	max_hibernated_echoes: number,
	current_active_count: number,
	current_hibernated_count: number,
	allows_travel: boolean,
	allows_global_events: boolean,
	description: string,
	era: string,
	region: string,
	tags: string[],
	// Total events generated in this Shard (reputation metric, ME-SDB-001 §9.2).
	total_events_generated?: number,
	updated_at: string,
};

export type ShardDetail = {
	shard_id: string,
	name: string,
	shard_type: string,
	status: string,
	description: string,
	era: string,
	region: string,
	tags: string[],
	current_active_count: number,
	current_hibernated_count: number,
	max_active_echoes: number,
	max_hibernated_echoes: number,
	allows_travel: boolean,
	tick_rate_modifier: number,
	created_at: string,
};

export type ShardEchoSummary = {
	echo_id: string,
	name: string,
	status: string,
	current_mood: string,
	current_location_id: string,
	current_tick: number,
};

export type ShardLocation = {
	location_id: string,
	shard_id: string,
	name: string,
	location_type: LocationType,
	description: string,
	capacity: number,
	connects_to: string[],
	travel_time_ticks: number,
	is_spawn_point: boolean,
	social_density: number,
	economic_activity: number,
	danger_level: number,
};

export type ShardPlacement = {
	echo_id: string,
	shard_id: string,
	location_id: string,
	arrived_at_tick: number,
	travel_state: TravelState,
	destination_id: string | null,
	arrival_tick: number | null,
};

export type ShardStatus = "Active" | "Paused" | "Archived" | "PendingDeletion";

export type ShardSummary = {
	shard_id: string,
	name: string,
	shard_type: string,
	status: string,
	description: string,
	current_active_count: number,
	current_hibernated_count: number,
	max_active_echoes: number,
	created_at: string,
};

export type ShardTheme = {
	theme_id: string,
	shard_id: string,
	setting_prompt: string,
	cultural_norms: string,
	economic_model: EconomicModel,
	technology_level: TechnologyLevel,
	conflict_style: ConflictStyle,
	available_occupations: string[],
	banned_elements: string[],
	custom_rules: string,
	shard_prompt_template: string | null,
	/**
	 *  Proper-noun-free visual description for image prompt generation.
	 *  Colors, lighting, composition, atmosphere, textures — no names, dates, or places.
	 */
	visual_style?: string | null,
	/**
	 *  Starting wealth for Echoes entering this Shard (fixed-point).
	 *  Default: 1000 (1.0 in fixed-point).
	 */
	starting_wealth: number,
};

export type ShardType = "Public" | "Private" | "Personal";

// Story export job for Echo timeline rendering. Reference: ME-UAD-001 §5.4.
export type StoryExport = {
	export_id: string,
	user_id: string,
	// Selected Echo IDs to export (one or more).
	echo_ids: string[],
	format: ExportFormat,
	status: ExportStatus,
	created_at: string,
	completed_at: string | null,
	download_path: string | null,
	// Subtitle file path for video exports.
	subtitle_path: string | null,
	// Optional date range filter (inclusive start).
	from_date: string | null,
	// Optional date range filter (inclusive end).
	to_date: string | null,
};

// Request body for story export.
export type StoryExportRequest = {
	// One or more Echo IDs to export.
	echo_ids: string[],
	format: ExportFormat,
	// Optional date range filter (ISO date, e.g. "2026-01-15").
	from_date: string | null,
	// Optional date range filter (ISO date, e.g. "2026-04-01").
	to_date: string | null,
};

// Response for story export.
export type StoryExportResponse = {
	export_id: string,
	format: string,
	status: string,
	created_at: string,
	download_path: string | null,
	subtitle_path: string | null,
};

export type SubscriptionStatus = "Active" | "PastDue" | "Cancelled" | "Expired";

export type SubscriptionTier = "Free" | "Core" | "Creator" | "GodMode";

export type TechnologyLevel = "Primitive" | "Industrial" | "Modern" | "NearFuture" | "FarFuture" | "Fantasy";

export type TravelRequest = {
	destination_shard_id: string,
};

export type TravelResponse = {
	status: string,
	arrival_tick: number | null,
	request_id: string | null,
	expires_at: string | null,
};

export type TravelState = "Stationary" | "Travelling";

// PUT /echoes/:id/persona — Edit persona text.
export type UpdatePersonaRequest = {
	persona_text: string | null,
	what_if_prompt?: string | null,
};

export type User = {
	user_id: string,
	email: string,
	email_verified: boolean,
	display_name: string,
	display_name_slug: string,
	account_type: AccountType,
	subscription_tier: SubscriptionTier,
	created_at: string,
	updated_at: string,
	last_login_at: string,
	account_status: AccountStatus,
	locale: string,
	timezone: string | null,
	onboarding_complete: boolean,
	tos_accepted_at: string,
	tos_version: string,
	privacy_accepted_at: string,
	privacy_version: string,
	/**
	 *  Echo count limit override. 0 = use tier default from config.
	 *  Non-zero = hard override (e.g., admin grant, beta reward).
	 *  Reference: ME-UAD-001 §6.1.
	 */
	echo_count_limit?: number,
	/**
	 *  When true, this user's Echoes never interact with other users' Echoes.
	 *  Reference: ME-PDP-001 (cross-user consent), ME-UAD-001 §4.
	 */
	solo_mode?: boolean,
	/**
	 *  When set, account will be purged after this date (30-day grace period).
	 *  Reference: ME-PDP-001 §5.3, ME-UAD-001 §5.1.
	 */
	deletion_scheduled_at?: string | null,
	/**
	 *  CCPA "Do Not Sell My Personal Information" flag.
	 *  When true, analytics_opt_out is also true.
	 *  Reference: ME-PDP-001 §4.3.
	 */
	do_not_sell?: boolean,
	/**
	 *  When true, client-side analytics events are discarded.
	 *  Linked to do_not_sell per ME-PDP-001.
	 */
	analytics_opt_out?: boolean,
	/**
	 *  When the current paid subscription expires. None = Free tier (no expiry).
	 *  Crypto payments set this to `now + duration_days`. Extension adds to existing.
	 */
	subscription_expires_at?: string | null,
	// Stripe customer ID (cus_...). Populated on first Stripe checkout.
	stripe_customer_id?: string | null,
	// Stripe subscription ID (sub_...). Populated on checkout.session.completed.
	stripe_subscription_id?: string | null,
};

export type UserInventory = {
	inventory_id: string,
	user_id: string,
	item_id: string,
	equipped: boolean,
	equipped_target_id: string | null,
	acquired_at: string,
};

export type UserProfile = {
	user_id: string,
	bio: string | null,
	avatar_hash: string | null,
	public_echo_feed: boolean,
	profile_visibility: ProfileVisibility,
	joined_shards: string[],
	echo_count: number,
	updated_at: string,
};

export type UserPurchase = {
	purchase_id: string,
	user_id: string,
	item_id: string,
	price_paid_cents: number,
	purchased_at: string,
	payment_reference: string,
};

export type UserRelationship = {
	relationship_id: string,
	source_user_id: string,
	target_user_id: string,
	relationship_type: UserRelationshipType,
	created_at: string,
};

export type UserRelationshipType = "Follow" | "Block" | "Mute";

export type UserReport = {
	report_id: string,
	reporter_user_id: string,
	target_type: ReportTargetType,
	target_id: string,
	reason: string,
	details?: string,
	status: ReportStatus,
	// Priority: 0 = P0 (imminent harm), 1 = P1, 2 = P2, 3 = P3 (lowest).
	priority: number,
	created_at: string,
	resolved_at: string | null,
	resolution: string | null,
};

export type UserSession = {
	session_id: string,
	user_id: string,
	refresh_token_hash: string,
	device_fingerprint: string | null,
	created_at: string,
	expires_at: string,
	last_used_at: string,
	revoked: boolean,
};

export type UserSubscription = {
	user_id: string,
	tier: SubscriptionTier,
	status: SubscriptionStatus,
	started_at: string,
	current_period_end: string,
	payment_provider_id: string | null,
	echo_count_limit: number,
	influence_points_daily: number,
	updated_at: string,
};

export type WaitlistCountResponse = {
	count: number,
};

// Waitlist entry for pre-launch signups. Reference: ME-UXF-001 §4.1.
export type WaitlistEntry = {
	entry_id: string,
	// Email address (encrypted at rest in production).
	email: string,
	// Queue position (auto-incremented, adjusted by referrals).
	position: number,
	// Unique referral code for this entry.
	referral_code: string,
	// entry_id of the user who referred this signup.
	referred_by: string | null,
	// UTM source tracking.
	source: string | null,
	status: WaitlistStatus,
	created_at: string,
	invited_at: string | null,
};

export type WaitlistPositionResponse = {
	entry_id: string,
	position: number,
	status: string,
	referral_code: string,
	referral_count: number,
};

export type WaitlistSignupRequest = {
	email: string,
	// Optional referral code from an existing waitlist member.
	referral_code: string | null,
	// UTM source tracking.
	source: string | null,
};

export type WaitlistSignupResponse = {
	entry_id: string,
	position: number,
	referral_code: string,
};

// Status of a waitlist entry. Reference: ME-UXF-001 §4.1.
export type WaitlistStatus = "Waiting" | "Invited" | "Registered" | "Declined";

// Envelope for all world events.
export type WorldEvent = {
	event_id: string,
	tick_id: number,
	timestamp: string,
	payload: WorldEventPayload,
};

// All event variants from the doc suite.
export type WorldEventPayload = { EchoCreated: { echo_id: string; owner_id: string } } | { EchoDeleted: { echo_id: string } } | { EchoHibernated: { echo_id: string; reason: string } } | { EchoWoken: { echo_id: string } } | 
// Emitted when a quarantined Echo is restored by admin. Phase 7.
{ EchoRestored: { echo_id: string } } | { TickStarted: { tick_id: number } } | { TickCompleted: { tick_id: number } } | { DiaryEntryGenerated: { echo_id: string; diary_id: string } } | { DiaryImageReady: { echo_id: string; diary_id: string; image_url: string } } | { LifeEventOccurred: { echo_id: string; event_id: string } } | { MoodChanged: { echo_id: string; old_mood: string; new_mood: string } } | { EchoInteraction: { echo_a: string; echo_b: string; interaction_type: string; tick_id: number } } | 
// Emitted from process_interaction_with_analytics when a new Echo relationship forms.
{ RelationshipFormed: { echo_a: string; echo_b: string } } | 
// Emitted when an existing Echo relationship changes type. Phase 7.
{ RelationshipChanged: { echo_a: string; echo_b: string } } | { ShardCreated: { shard_id: string; shard_type: string; owner_id: string } } | { ShardStatusChanged: { shard_id: string; old_status: string; new_status: string } } | { ShardTravelRequested: { echo_id: string; from_shard: string; to_shard: string } } | { ShardTravelApproved: { echo_id: string; destination_shard: string } } | { ShardTravelCompleted: { echo_id: string; shard_id: string } } | { ShardTravelDenied: { echo_id: string; reason: string } } | { ShardCapacityWarning: { shard_id: string; percent: number } } | { EchoMoved: { echo_id: string; shard_id: string; from_location: string; to_location: string; arrival_tick: number } } | { EchoWealthChanged: { echo_id: string; old_value: number; new_value: number; reason: string } } | { GlobalEventPropagated: { event_id: string; affected_shards: string[] } } | 
// Emitted by safety classifier on T2/T3 detection. Wired via record_content_flagged().
{ ContentFlagged: { content_id: string; tier: string } } | 
// Emitted when T3 content triggers Echo quarantine. Phase 7 safety enforcement.
{ EchoQuarantined: { echo_id: string; reason: string } } | 
// Phase 7 — emergent behavior detection.
{ EmergentGroupFlagged: { echo_ids: string[] } } | { InfluencePointUsed: { user_id: string; echo_id: string; points: number } } | { UserRegistered: { user_id: string } } | 
// Emitted by purge_user() after full data cascade. Requires EventBus in PurgeContext (Phase 7).
{ UserDeleted: { user_id: string } } | { PersonaUpdated: { echo_id: string; version: number } } | { ConversationSaved: { echo_id: string; user_id: string } } | 
// Phase 7 — user feedback system.
{ FeedbackSubmitted: { user_id: string; feedback_id: string } } | { CommunityMessagePosted: { channel_id: string; message_id: string; author_id: string } } | { MessageDeleted: { channel_id: string; message_id: string; deleted_by: string } } | { MessageEdited: { channel_id: string; message_id: string; author_id: string } } | { FeedItemGenerated: { feed_item_id: string; echo_id: string; shard_id: string } } | { UserFollowed: { source_user_id: string; target_user_id: string } } | { UserBlocked: { source_user_id: string; target_user_id: string } } | { UserMuted: { source_user_id: string; target_user_id: string } } | { NotificationCreated: { user_id: string; notification_id: string } } | 
// Emitted when the daily digest notification is generated. Phase 7 digest system.
{ DailyDigestGenerated: { user_id: string; notification_id: string } } | 
// Emitted when an Echo's AI-generated portrait is ready (background generation complete).
{ EchoAvatarReady: { echo_id: string; avatar_url: string } } | { EmergencyHibernation: { reason: string } };

// Events sent over the WebSocket to clients.
export type WsEchoEvent = { type: "DiaryEntryCreated"; echo_id: string; diary_id: string; tick_id: number } | { type: "DiaryImageReady"; echo_id: string; diary_id: string; image_url: string } | { type: "LifeEventOccurred"; echo_id: string; event_id: string; tick_id: number } | { type: "MoodChanged"; echo_id: string; mood: string; tick_id: number } | { type: "EchoMoved"; echo_id: string; from_location: string; to_location: string } | { type: "PersonaUpdated"; echo_id: string; version: number } | { type: "EchoHibernated"; echo_id: string; reason: string } | { type: "EchoWoken"; echo_id: string } | { type: "EchoWealthChanged"; echo_id: string; old_value: number; new_value: number; reason: string } | { type: "EchoDeleted"; echo_id: string } | { type: "ShardTravelCompleted"; echo_id: string; shard_id: string } | { type: "ShardCreated"; shard_id: string; shard_type: string } | { type: "CommunityMessagePosted"; channel_id: string; message_id: string; author_id: string } | { type: "CommunityMessageEdited"; channel_id: string; message_id: string; author_id: string } | { type: "CommunityMessageDeleted"; channel_id: string; message_id: string; deleted_by: string } | { type: "NotificationCreated"; notification_id: string } | { type: "EchoAvatarReady"; echo_id: string; avatar_url: string } | { type: "Connected"; echo_id: string; message: string } | { type: "Error"; message: string };
