// This file is auto-generated by `cargo run --bin generate-types`.
// Do not edit manually. Changes will be overwritten.
// Source: crates/shared/src/bin/generate_types.rs
// This file has been generated by Specta. Do not edit this file manually.
export type AcceptRequest = {
	invite_token: string,
};

export type AccessEntryResponse = {
	user_id: string,
	granted_at: string,
	granted_by: string,
};

export type AccountStatus = "Active" | "Suspended" | "PendingDeletion" | "Deleted";

/**
 *  Account role in the trust & safety hierarchy. Per ME-CSS-001 §9.1
 *  the three roles are:
 *  - **Standard** — ordinary user with no moderation powers.
 *  - **Moderator** — appointed by an Admin. Can mute users in channels
 *    (1hr–7 days), delete individual messages, and escalate items to
 *    an Admin. Cannot ban users, lock channels, or manage moderators.
 *  - **Admin** — full moderation powers. Seeded by the Founder (see
 *    `godmode seed-admin`); cannot be created or demoted via the API.
 * 
 *  Private Shard Owners get per-shard moderation powers through a
 *  separate shard-ownership check (ME-SDB-001), not through this
 *  enum, because ownership is scoped rather than account-global.
 */
export type AccountType = "Standard" | "Moderator" | "Admin";

export type ActiveConversationResponse = {
	conversation_id: string,
	echo_id: string,
	created_at: string,
	saved: boolean,
	// Whether this conversation was resumed (true) or newly created (false).
	resumed: boolean,
	// Preloaded messages if this was a resumed conversation.
	messages: ConversationMessageResponse[],
};

export type AdminPagination = {
	limit: number,
	offset?: number,
};

export type AdminUpsertItemRequest = {
	item_id?: string | null,
	name: string,
	description: string,
	item_type: MarketplaceItemType,
	rarity: ItemRarity,
	price_tier_required: SubscriptionTier,
	price_coins?: number | null,
	image_url?: string | null,
	is_available?: boolean | null,
};

// A single analytics event.
export type AnalyticsEvent = {
	id: string,
	user_id: string,
	event_name: string,
	created_at: string,
	source: EventSource,
};

// Query parameters for admin analytics.
export type AnalyticsQuery = {
	event_name: string | null,
	since: string | null,
	limit: number,
	offset?: number,
};

/**
 *  Aggregated daily summary for retention sweep.
 *  Reference: ME-PDP-001 §5.1, Task E1.
 */
export type AnalyticsSummary = {
	id: string,
	date: string,
	event_name: string,
	count: number,
	distinct_users: number,
};

// API key for third-party access. Reference: ME-API-001 §3.2.
export type ApiKey = {
	key_id: string,
	user_id: string,
	name: string,
	// Last 4 characters of the key for display.
	key_prefix: string,
	created_at: string,
	revoked_at: string | null,
};

export type ApiKeyListItem = {
	key_id: string,
	name: string,
	// Last 4 chars of the key.
	key_prefix: string,
	created_at: string,
};

/**
 *  Tier the user falls to when a `PromotionalSubscription` expires.
 *  Reference: ME-MIS-001 §7.2.
 * 
 *  Narrow variant set mirrors `GrantedTier`'s rationale: today every
 *  beta-reward promo auto-downgrades to Free, and the Core option
 *  exists for future Custom promos where a partial downgrade makes
 *  sense. Creator is intentionally absent — add when a grant flow
 *  needs it.
 *  `PartialOrd`/`Ord` derived so "pick most conservative auto-downgrade
 *  across overlapping expired promos" reduces to `.min()`.
 */
export type AutoDowngradeTier = "Free" | "Core";

export type BanRequest = {
	user_id: string,
	channel_id: string,
	reason: string,
};

// Request body for batch analytics event submission.
export type BatchEventsRequest = {
	events: ClientEvent[],
};

/**
 *  Beta invite code for gated registration.
 *  Reference: ME-UXF-001 §4.2.
 */
export type BetaInvite = {
	id: string,
	code: string,
	// Email address the invite was issued to (for auto-claim on registration).
	email?: string | null,
	created_by: string,
	claimed_by: string | null,
	claimed_at: string | null,
	expires_at: string,
	created_at: string,
};

export type BetaInviteResponse = {
	id: string,
	code: string,
	created_by: string,
	claimed_by: string | null,
	claimed_at: string | null,
	expires_at: string,
	created_at: string,
};

/**
 *  Tracks whether a user participated in beta, what phase they were
 *  in, and whether the Founding Echo badge has been granted.
 * 
 *  Primary key: `user_id` (one record per user).
 * 
 *  `feedback_count` is currently an unused placeholder. No feedback
 *  submission flow exists in the codebase yet; when one ships, the
 *  increment call will live alongside the submission handler. Until
 *  then the field is always 0 for new records. Reference: ME-MIS-001
 *  §7.3 clarification.
 */
export type BetaParticipation = {
	user_id: string,
	/**
	 *  Locked at creation. A tester invited to closed beta who didn't
	 *  accept until after open beta opened is still `ClosedBeta`.
	 */
	beta_tier: BetaTier,
	joined_at: string,
	// Placeholder until a feedback submission flow ships. Default 0.
	feedback_count?: number,
	/**
	 *  Flips to `true` when the Founding Echo `MarketplaceItem` is
	 *  added to the user's `UserInventory`. Gate for idempotency in
	 *  `godmode grant-beta-rewards` so re-runs don't double-grant.
	 */
	badge_granted: boolean,
};

/**
 *  Classification of a beta tester for reward granting.
 *  Reference: ME-MIS-001 §7.3.
 * 
 *  - `ClosedBeta` — tester admitted during closed beta phases 1–3
 *    (first 25 + random 50 + random 25 waitlist draws, 100 testers
 *    total). At public launch receives a 3-month God Mode
 *    `PromotionalSubscription`.
 *  - `OpenBeta` — tester admitted during open beta phase 4 (remainder
 *    of the waitlist). At public launch receives a 1-month Core
 *    `PromotionalSubscription`.
 * 
 *  Enum is not changeable post-creation — a user's beta tier is fixed
 *  by the phase they joined in. A tester invited to closed beta who
 *  didn't accept until after open beta opened is still `ClosedBeta`.
 */
export type BetaTier = "ClosedBeta" | "OpenBeta";

/**
 *  GDPR Article 33 breach record-keeping.
 *  Reference: ME-PDP-001 §6.2.
 */
export type BreachRecord = {
	id: string,
	detected_at: string,
	severity: BreachSeverity,
	description: string,
	affected_user_count: number,
	response_actions: string[],
	notified_authorities: boolean,
	notified_users: boolean,
	resolved_at: string | null,
	created_by: string,
	/**
	 *  Source of the record — `Manual` means an admin filed it through
	 *  the API; `Automated` means the runtime detector emitted it.
	 *  Defaulted via serde for back-compat with rows written before
	 *  this field existed.
	 */
	source?: BreachSource,
};

export type BreachRecordResponse = {
	id: string,
	detected_at: string,
	severity: string,
	description: string,
	affected_user_count: number,
	response_actions: string[],
	notified_authorities: boolean,
	notified_users: boolean,
	resolved_at: string | null,
	created_by: string,
};

/**
 *  Severity level for GDPR breach records.
 *  Reference: ME-PDP-001 §6.2.
 */
export type BreachSeverity = "Low" | "Medium" | "High" | "Critical";

export type BreachSource = "Manual" | "Automated";

export type CSAMIncident = {
	id: string,
	created_at: string,
	// Uploader whose account is the subject of enforcement.
	user_id: string,
	// URL of the matched content at the edge (Cloudflare notification).
	image_url: string,
	/**
	 *  Date on Cloudflare's notification email — distinct from `created_at`
	 *  because the admin may file the incident record hours after the
	 *  daily digest lands.
	 */
	cloudflare_notification_date: string,
	/**
	 *  NCMEC CyberTipline report number once filed. `None` until the
	 *  operator files the report and records it via `PATCH
	 *  /admin/csam-incidents/{id}`.
	 */
	ncmec_report_id: string | null,
	/**
	 *  Regional-equivalent report identifier (e.g. Singapore SPF
	 *  e-services reference). `None` if no regional filing is required
	 *  per `docs/runbooks/csam-incident-response.md`.
	 */
	regional_report_id: string | null,
	/**
	 *  R2 object key of the encrypted evidence bundle. Always present
	 *  after creation; fetching the bytes requires the preservation
	 *  key and a signed one-time URL.
	 */
	preservation_bundle_path: string,
	/**
	 *  SHA-256 hex digest of the preservation key used to encrypt this
	 *  bundle. Pinning the fingerprint on each incident lets a future
	 *  key-rotation migration identify which rows need re-encryption
	 *  without exposing any key material.
	 */
	preservation_key_fingerprint: string,
	status: CSAMIncidentStatus,
	// Free-text admin notes (sanitised at ingress). Max 10,000 chars.
	notes?: string,
	/**
	 *  When `true`, the preservation bundle is retained indefinitely,
	 *  overriding the 90-day default. Set during active law-enforcement
	 *  investigations.
	 */
	preservation_locked?: boolean,
};

export type CSAMIncidentResponse = {
	id: string,
	created_at: string,
	user_id: string,
	image_url: string,
	cloudflare_notification_date: string,
	ncmec_report_id: string | null,
	regional_report_id: string | null,
	preservation_bundle_path: string,
	preservation_key_fingerprint: string,
	status: CSAMIncidentStatus,
	notes: string,
	preservation_locked: boolean,
};

export type CSAMIncidentStatus = 
/**
 *  Incident filed, evidence preserved, enforcement applied. No
 *  external reports filed yet.
 */
{ state: "preserved" } | 
// NCMEC and/or regional report filed. Report IDs recorded.
{ state: "reported" } | 
/**
 *  Law enforcement notified / engaged. Typically paired with
 *  `preservation_locked = true`.
 */
{ state: "law_enforcement_notified" } | 
/**
 *  Incident closed. `reason` carries the disposition — closure
 *  semantics are NOT interchangeable:
 *    - `FalsePositive` → enforcement reversed
 *    - `ResolvedAfterReporting` → enforcement preserved
 */
{ state: "closed"; reason: ClosureReason };

export type CancelRequest = {
	session_id: string,
};

export type ChangePasswordRequest = {
	current_password: string,
	new_password: string,
};

export type Channel = {
	channel_id: string,
	name: string,
	channel_type: ChannelType,
	scope_id: string | null,
	created_at: string,
	status: ChannelStatus,
	description: string,
	is_read_only: boolean,
	slow_mode_seconds: number,
};

export type ChannelMessage = {
	message_id: string,
	channel_id: string,
	author_id: string,
	content: string,
	message_type: MessageType,
	reply_to: string | null,
	created_at: string,
	edited_at: string | null,
	is_deleted: boolean,
	attached_echo_id: string | null,
	attached_export_id: string | null,
	// Discord CDN URL for image attachments.
	image_url?: string | null,
	// JSON-serialized poll data (question, options, votes).
	poll_data?: string | null,
};

export type ChannelResponse = {
	channel_id: string,
	name: string,
	channel_type: ChannelType,
	scope_id: string | null,
	status: ChannelStatus,
	description: string,
	is_read_only: boolean,
	slow_mode_seconds: number,
	created_at: string,
};

export type ChannelStatus = "Active" | "Archived" | "Locked";

export type ChannelType = "Shard" | "Global" | "Topic" | "PrivateShard" | "Event";

/**
 *  A single client-side event.
 * 
 *  `properties` is an arbitrary JSON object. The server persists it as
 *  the untyped `serde_json::Value` it really is; the [`JsonObject`]
 *  wrapper exists purely so specta 2.0.0-rc.23 can export the
 *  containing types without overflowing the exporter stack (its
 *  built-in `Type for serde_json::Value` recurses infinitely). See
 *  [`crate::specta_support::JsonObject`].
 * 
 *  [`JsonObject`]: crate::specta_support::JsonObject
 */
export type ClientEvent = {
	event_name: string,
	properties?: Record<string, never>,
};

export type ClosureReason = 
/**
 *  Report accepted by NCMEC/LE, no further platform action needed.
 *  User remains suspended; echoes remain quarantined.
 */
"resolved_after_reporting" | 
/**
 *  Cloudflare's post-review confirmed the match was a false
 *  positive. The admin PATCH that closes the incident in this
 *  state automatically reactivates the user and un-quarantines
 *  the echoes.
 */
"false_positive";

export type CommitRequest = {
	session_id: string,
};

export type ConflictStyle = "Peaceful" | "Political" | "Economic" | "Military" | "Survival";

export type ConsentRecord = {
	consent_id: string,
	user_id: string,
	consent_type: ConsentType,
	version: string,
	granted_at: string,
	withdrawn_at: string | null,
	ip_hash: string,
	context: string,
};

export type ConsentType = "ToS" | "Privacy" | "PersonaData" | "CrossUserInteraction" | "Community";

export type ContentFlag = {
	flag_id: string,
	tick_id: number,
	echo_id: string,
	tier: ContentTierEnum,
	raw_content_hash: string,
	classification_reason: string,
	action_taken: string,
	reviewed_by: string | null,
	review_timestamp: string | null,
};

export type ContentTierEnum = "T0" | "T1" | "T2" | "T3";

// Direct conversation between a user and their Echo. Reference: ME-UXF-001 §7.7.
export type Conversation = {
	conversation_id: string,
	echo_id: string,
	user_id: string,
	created_at: string,
	saved: boolean,
};

// A message in a direct Echo conversation.
export type ConversationMessage = {
	message_id: string,
	conversation_id: string,
	role: ConversationRole,
	content: string,
	created_at: string,
};

export type ConversationMessageResponse = {
	message_id: string,
	// Role, lowercased (`"user"` or `"echo"`).
	role: string,
	content: string,
	created_at: string,
};

export type ConversationResponse = {
	conversation_id: string,
	echo_id: string,
	created_at: string,
	saved: boolean,
};

// Role in a direct Echo conversation.
export type ConversationRole = "User" | "Echo";

export type CreateApiKeyRequest = {
	name: string,
};

export type CreateApiKeyResponse = {
	key_id: string,
	name: string,
	// The raw API key — shown once, never again.
	key: string,
	created_at: string,
};

export type CreateBetaInviteRequest = {
	expires_in_days: number | null,
};

export type CreateBreachRecordRequest = {
	severity: string,
	description: string,
	affected_user_count: number,
	response_actions: string[],
};

export type CreateCSAMIncidentRequest = {
	user_id: string,
	image_url: string,
	// RFC-3339 timestamp of the Cloudflare notification email.
	cloudflare_notification_date: string,
	/**
	 *  Base64-encoded image bytes. Optional — the runbook walks the
	 *  operator through pulling bytes from origin storage; if they
	 *  cannot be recovered (e.g. the origin was already purged), the
	 *  bundle preserves metadata-only and this field is omitted.
	 *  Max 5 MiB after base64 decode (~6.67 MiB of base64 input).
	 */
	image_bytes_b64: string | null,
	// If the image was an echo avatar, which echo.
	echo_id: string | null,
	notes: string | null,
};

export type CreateCSAMIncidentResponse = {
	incident: CSAMIncidentResponse,
	enforcement: EnforcementSummary,
};

export type CreateChannelRequest = {
	name: string,
	description: string | null,
	channel_type: ChannelType,
	is_read_only: boolean | null,
	slow_mode_seconds: number | null,
};

// POST /echoes — Create a new Echo.
export type CreateEchoRequest = {
	name: string,
	persona_text: string,
	what_if_prompt: string,
	age_at_creation?: number | null,
	persona_mode?: string | null,
	consent_declaration: boolean,
	// Optional: create Echo in a specific Public Shard instead of Personal Shard.
	shard_id?: string | null,
	/**
	 *  Optional free-text physical description. When present and non-empty,
	 *  it is used directly as the FLUX.2 portrait prompt and the LLM
	 *  descriptor extraction from `persona_text` is skipped.
	 */
	physical_description?: string | null,
};

export type CreateGlobalEventRequest = {
	name: string,
	description: string,
	event_type: GlobalEventType,
	// Fixed-point intensity 0–1000 (0.0–1.0).
	intensity: number,
	// Shard IDs to affect. None/empty = all shards.
	affected_shards: string[] | null,
	start_tick: number,
	duration_ticks: number,
};

export type CreateGroupRequest = {
	name: string,
};

export type CreatePollRequest = {
	question: string,
	options: string[],
};

export type CreatePrivateShardRequest = {
	name: string,
	description: string,
	base_template: string,
};

export type CreatePublicShardRequest = {
	template_name: string,
};

export type CreateReportRequest = {
	target_type: string,
	target_id: string,
	reason: string,
	details: string | null,
};

export type DataAccessLog = {
	log_id: string,
	accessor_id: string,
	target_id: string | null,
	access_type: DataAccessType,
	resource: string,
	reason: string,
	timestamp: string,
	/**
	 *  Restricted-access marker (ME-PDP-001 §6.3; ME-TSP-001 §2.2).
	 *  Set to `true` for accesses to content or metadata that is
	 *  itself legally restricted — currently only CSAM evidence
	 *  bundles and the admin endpoints that manipulate their
	 *  incident records. The `/admin/audit-log` endpoint surfaces
	 *  this flag so restricted accesses can be queried separately.
	 */
	restricted?: boolean,
};

export type DataAccessType = "Read" | "Export" | "Modify" | "Delete" | "AdminView";

// Data export request (Right of Access). Reference: ME-PDP-001 §4.
export type DataExport = {
	export_id: string,
	user_id: string,
	status: ExportStatus,
	created_at: string,
	completed_at: string | null,
	download_path: string | null,
};

/**
 *  Permanent ledger of deleted user IDs.
 *  Used for backup restoration — re-purge deleted users after restore.
 *  Reference: ME-PDP-001 §5.3.
 */
export type DeletionLedger = {
	id: string,
	// SHA-256 hash of the user_id, NOT the raw UUID.
	user_id_hash: string,
	deleted_at: string,
};

export type DetailedHealthResponse = {
	status: string,
	tick_rate_seconds: number,
	active_echo_count: number,
	memory_usage_mb: number,
	vram_usage_mb: number,
	version: string,
};

export type DiaryEntry = {
	diary_id: string,
	echo_id: string,
	tick_id: number,
	simulated_date: string,
	content: string,
	mood: string,
	location_name: string,
	shard_id: string,
	word_count: number,
	content_hash: string,
	// If this diary entry was influenced by a user nudge, the nudge text.
	nudge_source?: string | null,
	// URL of the generated scene image for this diary entry.
	image_url?: string | null,
	created_at: string,
};

/**
 *  GET /echoes/:id/diary — Cursor-paginated diary entries with optional
 *  mood filter. Reference: ME-API-001 §4.1 (cursor pagination) + §4.3.4.
 */
export type DiaryQuery = {
	cursor?: string | null,
	limit?: number | null,
	// Optional mood filter — when provided, only entries matching this mood are returned.
	mood: string | null,
};

// Discord account link. Reference: ME-CSS-001 §4.
export type DiscordLink = {
	user_id: string,
	discord_user_id: string,
	discord_username: string,
	linked_at: string,
	sync_display_name: boolean,
	/**
	 *  Discord OAuth access token. At rest AES-256-GCM ciphertext when
	 *  `tokens_encrypted == true`; API / handler reads always receive
	 *  plaintext because the repository decrypts on read. Reference:
	 *  ME-UAD-001 §9.1, ME-PDP-001 §6.1.
	 */
	access_token?: string | null,
	// Discord OAuth refresh token, same contract as `access_token`.
	refresh_token?: string | null,
};

export type DiscordLinkResponse = {
	discord_user_id: string,
	discord_username: string,
	linked_at: string,
	sync_display_name: boolean,
};

export type DiscordLinkStatus = {
	linked: boolean,
	discord_user_id: string | null,
	discord_username: string | null,
	sync_display_name: boolean | null,
};

/**
 *  A staged downgrade awaiting per-shard decisions.
 * 
 *  Schema notes:
 *  - `stripe_event_id` is the idempotency key. A replay of the same
 *    Stripe webhook event (network retry, test double-fire) looks up
 *    by this key and returns the existing session — never creates a
 *    duplicate.
 *  - `picked_included_shard_id` is `Some` only for God Mode → Creator
 *    sessions after the user's `pick-included-shard` call. Other
 *    downgrades never set it.
 *  - `pending_decisions` is keyed by `shard_id`. Every shard that
 *    lost an Included slot on this downgrade has an entry. For God
 *    Mode → Creator, the shard the user picks to keep Included is
 *    REMOVED from `pending_decisions` (only the 2 that still need a
 *    decision remain).
 */
export type DowngradeSession = {
	session_id: string,
	user_id: string,
	created_at: string,
	expires_at: string,
	old_tier: SubscriptionTier,
	new_tier: SubscriptionTier,
	stripe_event_id: string,
	state: DowngradeSessionState,
	/**
	 *  God Mode → Creator only: the shard the user selected to keep
	 *  Included. `None` for every other downgrade or before the user
	 *  calls `pick-included-shard`.
	 */
	picked_included_shard_id: string | null,
	pending_decisions: { [key in string]: PendingDecision },
};

/**
 *  DowngradeSession lifecycle state.
 * 
 *  Non-terminal: `PickingIncluded` / `AwaitingShardDecisions`.
 *  Terminal: `Committed` / `Expired` / `Cancelled`.
 */
export type DowngradeSessionState = 
/**
 *  God Mode → Creator only. User must select 1 of 3 shards that
 *  retains Included status before per-shard decisions begin.
 */
"PickingIncluded" | 
// Normal state: user makes per-shard decisions.
"AwaitingShardDecisions" | 
// Terminal: all decisions applied.
"Committed" | 
/**
 *  Terminal: 24h window elapsed without commit; Undecided and
 *  UpgradeBack shards defaulted to Archive.
 */
"Expired" | 
/**
 *  Terminal: user explicitly abandoned the session (no shard
 *  changes applied; tier change remains in effect per the soft-
 *  staging resolution for Flag A).
 */
"Cancelled";

/**
 *  Public-facing view of a [DowngradeSession] for the choice-flow
 *  client. Excludes the Stripe event id (internal idempotency only).
 */
export type DowngradeSessionView = {
	session_id: string,
	created_at: string,
	expires_at: string,
	old_tier: string,
	new_tier: string,
	state: string,
	picked_included_shard_id: string | null,
	pending_decisions: PendingDecisionEntry[],
};

export type Echo = {
	echo_id: string,
	owner_user_id: string,
	name: string,
	/**
	 *  Persona prompt at rest holds AES-256-GCM ciphertext whenever
	 *  `persona_text_encrypted == true`; API responses always emit
	 *  plaintext because the repository decrypts on read. Immutable after
	 *  creation (see `birth_hash` derivation in ME-UAD-001 §2.4). Reference:
	 *  ME-UAD-001 §9.1, ME-PDP-001 §6.1.
	 */
	persona_text: string,
	// What-if prompt, same encryption contract as `persona_text`.
	what_if_prompt: string,
	persona_mode: PersonaMode,
	/**
	 *  Orpheus-TTS preset voice assigned to this Echo by the persona→voice
	 *  classifier. `None` for Echoes predating Stage 4 backfill; populated
	 *  once at Echo creation (persona is immutable per ME-UAD-001 §2.4, so
	 *  the voice assignment never needs to be re-computed).
	 */
	voice_preset?: OrpheusVoice | null,
	/**
	 *  UTC timestamp of the classifier assignment for `voice_preset`.
	 *  Set once at creation; never re-assigned (persona is immutable).
	 */
	voice_assigned_at?: string | null,
	status: EchoStatus,
	age_at_creation: number,
	current_mood: string,
	current_tick: number,
	// Global tick_id when this Echo was first processed. Used for per-Echo relative time.
	birth_tick_id?: number,
	current_shard_id: string,
	current_location_id: string,
	memory_token_count: number,
	last_summarised_at: number,
	relationship_count: number,
	/**
	 *  Echo's current wealth in the Shard's economy (fixed-point).
	 *  Resets to destination Shard's starting_wealth on inter-Shard travel.
	 */
	wealth?: number,
	consent_declaration: boolean,
	consent_timestamp: string,
	birth_hash: string,
	created_at: string,
	updated_at: string,
	hibernated_at: string | null,
	deleted_at: string | null,
	/**
	 *  URL of the AI-generated portrait image (face, generated once at creation from bio).
	 *  Used as the MuseTalk reference face for voice sessions.
	 */
	avatar_url?: string | null,
	/**
	 *  Optional free-text physical description supplied at Echo creation.
	 *  When present and non-empty, this is used DIRECTLY as the FLUX.2
	 *  portrait prompt (with the shard's `visual_style` appended), bypassing
	 *  the LLM extraction step from `persona_text`. Introduced 2026-04-05.
	 *  Older Echoes deserialise with `None` via `#[serde(default)]`.
	 */
	physical_description?: string | null,
	/**
	 *  TTS voice description for VoxCPM2 diary narration. ~20 words describing
	 *  gender, age, accent, tone, energy. Generated from `physical_description`
	 *  via a short LLM call at Echo creation. Older Echoes deserialise with
	 *  `None` and get a voice_description backfilled lazily on first narration.
	 */
	voice_description?: string | null,
};

export type EchoListQuery = {
	limit: number,
	offset?: number,
};

export type EchoMemory = {
	memory_id: string,
	echo_id: string,
	source_tick_id: number,
	memory_type: MemoryType,
	content: string,
	emotional_valence: number,
	importance: number,
	embedding_id: string,
	is_summarised: boolean,
	summarised_from: string[],
	created_at: string,
	last_accessed_tick: number,
};

export type EchoRelationship = {
	relationship_id: string,
	echo_a_id: string,
	echo_b_id: string,
	relationship_type: EchoRelationshipType,
	status: RelationshipStatus,
	formed_at_tick: number,
	last_interaction_tick: number,
	sentiment: number,
	key_moments: string[],
	is_cross_user: boolean,
	cross_user_consent: boolean,
	created_at: string,
	updated_at: string,
};

export type EchoRelationshipType = "Friend" | "Rival" | "RomanticPartner" | "Colleague" | "Acquaintance" | "Family" | "Mentor" | "Adversary";

export type EchoResponse = {
	echo_id: string,
	name: string,
	persona_text: string,
	what_if_prompt: string,
	status: string,
	current_mood: string,
	current_tick: number,
	current_shard_id: string,
	birth_hash: string,
	created_at: string,
	// URL of the AI-generated portrait image (face). Null if generation failed or pending.
	avatar_url: string | null,
	/**
	 *  Free-text physical description supplied at creation (optional).
	 *  Null for Echoes created before the field was introduced.
	 */
	physical_description: string | null,
	/**
	 *  Non-English original of `persona_text` as the user typed it. Only set
	 *  when the Echo was created by a user with `locale != "en"`. Clients
	 *  display this instead of the English canonical `persona_text`.
	 *  Reference: docs/claude/i18n-multilingual-tasks.md CC TASK 2 STEP 7.
	 */
	persona_text_original?: string | null,
	// Non-English original of `what_if_prompt`. See `persona_text_original`.
	what_if_prompt_original?: string | null,
	// Non-English original of `physical_description`. See `persona_text_original`.
	physical_description_original?: string | null,
	/**
	 *  Locale tag of the `*_original` fields (e.g. `"zh-Hans"`). Set iff any
	 *  `*_original` is set. Lets the client know which font stack / direction
	 *  to apply.
	 */
	original_locale?: string | null,
	/**
	 *  UTC instant this Echo entered hibernation, `None` while Active. Drives
	 *  the ME-MIS-001 §5.2 hibernated-Echo card banner and the 90-day
	 *  auto-deletion countdown referenced by ME-UAD-001 §5.3. Mirrors
	 *  `Echo.hibernated_at`.
	 */
	hibernated_at: string | null,
};

export type EchoStatus = "Active" | "Travelling" | "Hibernated" | "Quarantined" | "Deleted";

export type EconomicModel = "Capitalist" | "Socialist" | "Barter" | "PostScarcity" | "Feudal" | "Custom";

export type EditMessageRequest = {
	content: string,
};

export type EnforcementAction = {
	action_id: string,
	user_id: string | null,
	action_type: EnforcementActionType,
	reason: string,
	created_at: string,
	expires_at: string | null,
};

export type EnforcementActionType = "MessageDeleted" | "UserMuted" | "UserChannelBanned" | "ChannelLocked" | "Warning" | "Quarantine" | "Suspension" | "Ban" | "FalsePositiveRestoration" | 
/**
 *  Account action taken as a consequence of a Cloudflare CSAM
 *  Scanning Tool match (ME-TSP-001 §2.2). Emitted when an admin
 *  files a `CSAMIncident` record; the structured audit trail is
 *  the incident record itself (evidence bundle, NCMEC report id,
 *  regional report id, preservation-locked flag). See
 *  `crates/core/src/models/csam_incident.rs` and
 *  `crates/safety/src/csam_preservation.rs`.
 */
"CsamMatch";

/**
 *  Explicit list of enforcement actions taken on incident creation —
 *  makes the audit trail self-describing in the HTTP response (not
 *  only in log lines).
 */
export type EnforcementSummary = {
	user_suspended: boolean,
	sessions_revoked: boolean,
	echoes_quarantined: number,
	api_keys_revoked: number,
};

export type EquipRequest = {
	equipped: boolean,
};

/**
 *  Escalate an item to an Admin for review.
 * 
 *  Only Moderators (or, in a future expansion, Private Shard Owners
 *  scoped to their own shard) can call this. Admins get 400
 *  `ADMIN_CANNOT_ESCALATE` — there is no higher tier to escalate to.
 *  Standard users file reports via `/reports` instead.
 * 
 *  Creates a `ModerationAction` with `action_type: EscalatedToAdmin`.
 *  The admin resolves via `POST /admin/escalations/:action_id/resolve`.
 */
export type EscalateRequest = {
	// User being escalated (e.g. repeated offender needing ban).
	target_user_id: string | null,
	// Specific message being escalated.
	target_message_id: string | null,
	// Channel being escalated (e.g. needs locking).
	target_channel_id: string | null,
	// Why the moderator is escalating. Free-text, 1–2000 chars.
	reason: string,
};

export type EscalateResponse = {
	action_id: string,
	action_type: ModerationActionType,
	moderator_id: string,
	target_user_id: string | null,
	target_message_id: string | null,
	target_channel_id: string | null,
	reason: string,
	created_at: string,
};

export type EscalationItem = {
	action_id: string,
	moderator_id: string,
	target_user_id: string | null,
	target_message_id: string | null,
	target_channel_id: string | null,
	reason: string,
	created_at: string,
	resolved_at: string | null,
	resolved_by: string | null,
	resolution_notes: string | null,
};

// Source of an analytics event.
export type EventSource = "Client" | "Engine";

// Format for story export. Reference: ME-UAD-001 §5.4.
export type ExportFormat = "text" | "json" | "pdf" | "video" | "book";

export type ExportResponse = {
	export_id: string,
	status: string,
	created_at: string,
	download_path: string | null,
};

// Status of a data export request.
export type ExportStatus = "Processing" | "Complete" | "Failed";

export type FamilyGroup = {
	group_id: string,
	owner_user_id: string,
	name: string,
	created_at: string,
};

export type FamilyGroupResponse = {
	group_id: string,
	owner_user_id: string,
	name: string,
	created_at: string,
	members: FamilyMemberResponse[],
	/**
	 *  Policy surfaced so the client can disable "invite" once the cap
	 *  is reached without a second round-trip.
	 */
	max_members: number,
	// Caller's role in this group — `owner` or `member`.
	role: string,
};

export type FamilyMember = {
	member_id: string,
	group_id: string,
	/**
	 *  The invited account. `None` while the invite is outstanding and
	 *  the accepting user has not yet been resolved. Filled on
	 *  acceptance.
	 */
	user_id: string | null,
	/**
	 *  Email the invite was addressed to. Stored lower-cased at
	 *  insertion time so lookups are case-insensitive.
	 */
	invite_email: string,
	/**
	 *  SHA-256 hex of the raw invite token delivered to the invitee.
	 *  The raw token is returned to the owner exactly once (on
	 *  invite-creation) and never persisted.
	 */
	invite_token_hash: string,
	status: FamilyMemberStatus,
	invited_at: string,
	accepted_at: string | null,
	/**
	 *  The member's own `User.subscription_tier` at the moment they
	 *  transitioned from `Invited` to `Active`. Used to revert them on
	 *  removal/leave/group-delete. `None` until acceptance.
	 */
	tier_before_family: SubscriptionTier | null,
};

export type FamilyMemberResponse = {
	member_id: string,
	group_id: string,
	user_id: string | null,
	invite_email: string,
	status: FamilyMemberStatus,
	invited_at: string,
	accepted_at: string | null,
};

/**
 *  Membership status within a FamilyGroup. Reference: ME-MIS-001 §8.2.
 *  - `Invited`: token issued, not yet redeemed.
 *  - `Active`: accepted; member receives tier propagation.
 *  - `Removed`: soft-deleted historical row (kept so an old token can no
 *    longer be re-redeemed against the same group).
 */
export type FamilyMemberStatus = "Invited" | "Active" | "Removed";

export type FeedItem = {
	item_id: string,
	item_type: FeedItemType,
	echo_id: string,
	shard_id: string,
	owner_user_id: string,
	headline: string,
	body: string,
	significance_score: number,
	tick_id: number,
	created_at: string,
	is_public: boolean,
};

export type FeedItemResponse = {
	item_id: string,
	/**
	 *  Kind of feed item — diary entry, life event, etc. Mirror of
	 *  `me_core::models::enums::FeedItemType`.
	 */
	item_type: FeedItemType,
	echo_id: string,
	shard_id: string,
	// Serialised as "title" to match client FeedItem type.
	title: string,
	body: string,
	// Serialised as "significance" to match client FeedItem type.
	significance: number,
	tick_id: number,
	created_at: string,
	is_public: boolean,
	/**
	 *  Locale of the `title` + `body` fields. Either the requesting user's
	 *  locale (translation found in `content_translations`) or `"en"`
	 *  (English canonical form — translation not yet stored by the
	 *  outbound worker). Clients render `<TranslationPending>` when
	 *  `content_locale` is `"en"` for non-English users.
	 *  CC TASK 3 Step 3.
	 */
	content_locale: string,
	/**
	 *  True iff the authoring Echo's owner owns the Founding Echo badge.
	 *  Computed once per response via a single batched
	 *  `UserInventoryRepository::get_founding_echo_owners` call over
	 *  the page's unique `owner_user_id`s. See ME-MIS-001 §7.3.
	 */
	owner_is_founding_echo: boolean,
};

export type FeedItemType = "diary_entry" | "life_event" | "relationship_change" | "achievement" | "global_event_participation" | "user_shared";

export type FeedQuery = {
	// Optional Echo ID filter. If provided, only feed items for that Echo are returned.
	echo_id: string | null,
	/**
	 *  Opaque pagination cursor from the previous response's
	 *  `next_cursor`. Omit for the first page.
	 */
	cursor?: string | null,
	/**
	 *  Maximum items to return on this page. Clamped server-side to
	 *  `MAX_PAGE_SIZE`. Omit for the server default.
	 */
	limit?: number | null,
};

// Context snapshot captured at the time of feedback submission.
export type FeedbackContext = {
	screen: string,
	echo_id?: string | null,
	shard_id?: string | null,
	recent_events?: string[],
};

export type FeedbackEntry = {
	feedback_id: string,
	user_id: string,
	feedback_type: FeedbackType,
	user_message: string,
	structured_summary: string,
	context: FeedbackContext,
	status: FeedbackStatus,
	priority?: FeedbackPriority | null,
	github_issue_url?: string | null,
	resolution_notes?: string | null,
	created_at: string,
	updated_at: string,
};

/**
 *  Mirror of `me_core::models::feedback::FeedbackEntry` with
 *  `utoipa::ToSchema`. Foreign enum fields use openapi_schemas mirrors.
 *  `DateTime<Utc>` fields are kept as-is (not converted to String) so
 *  chrono's serde serialization produces the `Z`-suffix format that
 *  matches the original me-core wire shape byte-for-byte.
 *  Mirror of `me_core::models::feedback::FeedbackEntry` with both
 *  `utoipa::ToSchema` and `specta::Type`. Foreign enum fields are
 *  serialized as their serde representation (PascalCase strings) and
 *  declared as String in the schema — the `#[schema(value_type)]`
 *  approach conflicts with specta's derive, so we accept the less-
 *  precise "string" schema in exchange for correct TypeScript codegen.
 *  `DateTime<Utc>` fields are kept as-is so chrono's serde produces
 *  the `Z`-suffix format matching the original me-core wire shape.
 */
export type FeedbackEntryView = {
	feedback_id: string,
	user_id: string,
	feedback_type: FeedbackType,
	user_message: string,
	structured_summary: string,
	context: FeedbackContext,
	status: FeedbackStatus,
	priority: FeedbackPriority | null,
	github_issue_url: string | null,
	resolution_notes: string | null,
	created_at: string,
	updated_at: string,
};

export type FeedbackPriority = "P0" | "P1" | "P2" | "P3" | "P4";

export type FeedbackStatus = "New" | "Acknowledged" | "Resolved" | "Wontfix";

export type FeedbackType = "Bug" | "FeatureRequest" | "Frustration" | "Praise" | "General";

/**
 *  A global event that affects one or more Shards.
 *  Reference: ME-SDB-001 §7.1.
 */
export type GlobalEvent = {
	event_id: string,
	name: string,
	description: string,
	event_type: GlobalEventType,
	// Intensity: fixed-point 0–1000 (0.0–1.0).
	intensity: number,
	// Affected shard IDs. Empty = all active Shards.
	affected_shards: string[],
	start_tick: number,
	duration_ticks: number,
	status: GlobalEventStatus,
	created_at: string,
};

export type GlobalEventResponse = {
	event_id: string,
	name: string,
	description: string,
	event_type: GlobalEventType,
	intensity: number,
	affected_shards: string[],
	start_tick: number,
	duration_ticks: number,
	status: GlobalEventStatus,
	created_at: string,
};

// Lifecycle status of a global event.
export type GlobalEventStatus = "Scheduled" | "Active" | "Completed";

/**
 *  Types of global events that affect Shards.
 *  Reference: ME-SDB-001 §7.1.
 */
export type GlobalEventType = "Economic" | "Social" | "Environmental" | "Political" | "Cultural";

export type GlobalSearchQuery = {
	q: string,
	/**
	 *  Optional filter — one of: `echoes | shards | diary | events | messages | feed`.
	 *  Omitted = search all types and merge results.
	 */
	type: string | null,
	cursor?: string | null,
	limit: number,
};

export type GrantAccessRequest = {
	user_id: string,
};

/**
 *  Subset of `SubscriptionTier` that a `PromotionalSubscription` can
 *  grant. Reference: ME-MIS-001 §7.2.
 * 
 *  Narrower than `SubscriptionTier` because a promo is always an
 *  *upgrade*: granting Free or Starter as a promo has no meaning, and
 *  Creator is not used by any current reward shape. If a future promo
 *  needs Creator, add the variant — backward compatible because serde
 *  errors on unknown variants only when reading old data, and no Creator
 *  grants exist on disk today.
 *  `PartialOrd`/`Ord` derived so tier resolution can pick the highest
 *  active promo via a plain `sort()` / `.max_by_key()`. Order follows
 *  the canonical tier ladder (lower variant = lower tier).
 */
export type GrantedTier = "Core" | "GodMode";

export type HealthResponse = {
	status: string,
	tick_interval_seconds: number,
	// Epoch milliseconds when the last tick completed. 0 if no tick has run yet.
	last_tick_at: number,
};

/**
 *  Single-use download nonce for evidence-bundle access
 *  (`GET /admin/csam-incidents/{id}/evidence`). Consumed on first
 *  successful fetch; expires after `expires_at` regardless of use.
 */
export type IncidentEvidenceNonce = {
	nonce_id: string,
	incident_id: string,
	issued_to: string,
	issued_at: string,
	expires_at: string,
	// `true` once the one-time download has completed.
	consumed: boolean,
};

/**
 *  GET /echoes/:id/influence — Get influence balance for this Echo's owner.
 * 
 *  `daily_limit`, `remaining`, `used_today` are `Option<u32>`: `None`
 *  for uncapped tiers (GodMode) and `Some(n)` for finite caps. The
 *  Commit 3.5 sentinel retirement replaced the pre-existing
 *  `u32::MAX` unlimited marker on the wire with JSON `null`.
 */
export type InfluenceBalanceResponse = {
	echo_id: string,
	daily_limit: number | null,
	remaining: number | null,
	used_today: number | null,
};

// POST /echoes/:id/influence — Apply influence to an Echo.
export type InfluenceRequest = {
	suggestion: string,
	influence_type: string,
};

export type InfluenceResponse = {
	influence_id: string,
	remaining_points: number,
};

export type InventoryRowResponse = {
	inventory_id: string,
	item_id: string,
	acquired_at: string,
	equipped: boolean,
	price_paid_coins: number,
	/**
	 *  Embedded item metadata so a client can render the inventory without a
	 *  second round-trip. `None` iff the referenced item was deleted from
	 *  the catalog — surface the row anyway so the user sees a placeholder.
	 */
	item: MarketplaceItemResponse | null,
};

export type InviteRequest = {
	email: string,
};

export type InviteResponse = {
	member_id: string,
	invite_email: string,
	invite_token: string,
	status: FamilyMemberStatus,
	invited_at: string,
};

export type IssueEvidenceUrlResponse = {
	nonce_id: string,
	url: string,
	expires_at: string,
	preservation_key_fingerprint: string,
};

export type ItemListQuery = {
	cursor?: string | null,
	limit?: number | null,
	// Optional type filter — case-insensitive match on `MarketplaceItemType`.
	item_type?: string | null,
	// Optional rarity filter — case-insensitive match on `ItemRarity`.
	rarity?: string | null,
};

/**
 *  Rarity tier for marketplace items. Higher rarity can correspond to
 *  higher `price_tier_required`, but the two are independent fields so a
 *  free Common item and a Core-locked Legendary item can both exist.
 */
export type ItemRarity = "Common" | "Rare" | "Epic" | "Legendary";

export type LifeEvent = {
	event_id: string,
	echo_id: string,
	tick_id: number,
	event_type: LifeEventType,
	headline: string,
	narrative: string,
	significance_score: number,
	location_name: string,
	shard_id: string,
	related_echo_ids: string[],
	content_hash: string,
	created_at: string,
};

export type LifeEventType = "Career" | "Relationship" | "Personal" | "Conflict" | "Achievement" | "Travel" | "Health" | "Financial" | "Social" | "GlobalEvent" | 
/**
 *  Created when an Echo is deleted and related Echoes experience the
 *  departure as a narrative event ("X has vanished without a trace").
 */
"Departure";

export type ListChannelsQuery = {
	type: ChannelType | null,
};

export type ListMessagesQuery = {
	/**
	 *  Opaque pagination cursor (base64-encoded UUID of the last item on the
	 *  previous page). Previous field name `before` is still accepted as an
	 *  alias for back-compat with existing clients that send a raw UUID.
	 *  Reference: ME-API-001 §4.1.
	 */
	cursor?: string | null,
	before?: string | null,
	after: string | null,
	limit: number | null,
};

export type LocationType = "Residential" | "Commercial" | "Social" | "Workplace" | "Transit" | "Landmark" | "Wilderness";

export type MarketplaceCategory = "DashboardTheme" | "PortraitStyle" | "ExportTemplate" | "ShardAesthetic" | "ScenarioPack" | "SeasonalCosmetic" | "SoundPack";

export type MarketplaceItem = {
	item_id: string,
	name: string,
	description: string,
	category: MarketplaceCategory,
	price_cents: number,
	is_available: boolean,
	is_limited_time: boolean,
	available_from: string | null,
	available_until: string | null,
	preview_asset: string,
	creator_id: string | null,
	content_hash: string,
	created_at: string,
};

export type MarketplaceItemResponse = {
	item_id: string,
	name: string,
	description: string,
	item_type: MarketplaceItemType,
	rarity: ItemRarity,
	price_tier_required: SubscriptionTier,
	price_coins: number,
	image_url: string | null,
	is_available: boolean,
	created_at: string,
};

/**
 *  Category of item sold on the marketplace. Reference: ME-API-001 §4.3.9,
 *  ME-CSS-001 §7.
 */
export type MarketplaceItemType = 
// Cosmetic skin applied to an Echo portrait / card accent.
"EchoSkin" | 
// Visual theme applied to a Shard (parallax, color palette).
"ShardTheme" | 
// Diary narration preset (font, frame, header animation).
"DiaryStyle" | 
// Profile badge awarded or purchased.
"Badge";

export type MemoryType = "Episodic" | "Semantic" | "Emotional" | "Relationship" | "Summarised";

export type MessageResponse = {
	message_id: string,
	channel_id: string,
	author_id: string,
	author_display_name: string,
	content: string,
	message_type: MessageType,
	created_at: string,
	edited_at: string | null,
	is_edited: boolean,
	can_edit: boolean,
	can_delete: boolean,
	image_url: string | null,
	poll_data: string | null,
	/**
	 *  True iff the message's `author_id` owns the Founding Echo badge.
	 *  Computed once per response via a single batched
	 *  `UserInventoryRepository::get_founding_echo_owners` call. See
	 *  ME-MIS-001 §7.3.
	 */
	owner_is_founding_echo: boolean,
};

export type MessageType = "UserMessage" | "SystemMessage" | "EchoHighlight";

/**
 *  A moderation action taken by a Moderator or Admin in a channel.
 *  Reference: ME-CSS-001 §9.2.
 */
export type ModerationAction = {
	action_id: string,
	moderator_id: string,
	target_user_id: string | null,
	target_message_id: string | null,
	target_channel_id: string | null,
	action_type: ModerationActionType,
	reason: string,
	// Duration in seconds (for timed mutes). None = permanent.
	duration_seconds: number | null,
	created_at: string,
	expires_at: string | null,
	/**
	 *  For `EscalatedToAdmin` actions only: timestamp when an Admin
	 *  marked the escalation resolved. `None` = still pending admin
	 *  review. Always `None` for non-escalation action types.
	 */
	resolved_at?: string | null,
	/**
	 *  Admin user id that resolved the escalation. Paired with
	 *  `resolved_at`.
	 */
	resolved_by?: string | null,
	/**
	 *  Admin's resolution notes — what action was taken (ban, no-op,
	 *  etc.). Free-text, sanitised at ingress.
	 */
	resolution_notes?: string | null,
};

/**
 *  Types of moderation actions in the community system.
 *  Reference: ME-CSS-001 §9.2.
 */
export type ModerationActionType = 
// Mute a user in a specific channel (timed).
"ChannelMute" | 
// Ban a user from a specific channel (permanent until removed).
"ChannelBan" | 
// Delete a message globally.
"MessageDelete" | 
// Lock a channel (no new messages).
"ChannelLock" | 
/**
 *  Moderator or Private Shard Owner hands an item off to an Admin
 *  for review. The `target_*` fields identify what is being
 *  escalated; the admin resolves via
 *  `POST /admin/escalations/:action_id/resolve`.
 */
"EscalatedToAdmin";

export type ModerationResponse = {
	action_id: string,
	action_type: ModerationActionType,
	moderator_id: string,
	target_user_id: string | null,
	target_channel_id: string | null,
	reason: string,
	expires_at: string | null,
	created_at: string,
};

export type ModeratorUserItem = {
	user_id: string,
	email: string,
	display_name: string,
	account_type: AccountType,
	updated_at: string,
};

export type MuteRequest = {
	user_id: string,
	channel_id: string,
	duration_seconds: number,
	reason: string,
};

export type Notification = {
	notification_id: string,
	user_id: string,
	category: NotificationCategory,
	title: string,
	body: string,
	link: string,
	read: boolean,
	created_at: string,
};

export type NotificationCategory = "EchoLifeEvent" | "DailyDigest" | "Social" | "Community" | "ShardActivity" | "Platform" | "Marketplace" | "Billing" | "Moderation" | "Account";

export type NotificationDelivery = "Off" | "InApp" | "InAppAndEmail";

export type NotificationPreferences = {
	user_id: string,
	echo_life_events: NotificationDelivery,
	daily_digest: NotificationDelivery,
	social: NotificationDelivery,
	community: NotificationDelivery,
	shard_activity: NotificationDelivery,
	platform: NotificationDelivery,
	marketplace: NotificationDelivery,
	billing: NotificationDelivery,
	moderation: NotificationDelivery,
	account: NotificationDelivery,
	quiet_hours_start: string | null,
	quiet_hours_end: string | null,
	updated_at: string,
};

export type NotificationQuery = {
	limit: number,
	unread_only?: boolean,
};

export type OAuthCallbackParams = {
	code: string,
	state: string,
};

export type OAuthInitResponse = {
	// The Discord authorization URL the client should redirect to.
	auth_url: string,
};

export type OracleAskRequest = {
	question: string,
	// Legacy field names (from server-side callers).
	context_type: string | null,
	context_id: string | null,
	// Client sends context as a nested object.
	context: OracleContextPayload | null,
	/**
	 *  Conversation history for session continuity. Capped at 50
	 *  messages to bound prompt size and prevent DoS via unbounded
	 *  arrays. Each message's text is capped at 2000 chars via
	 *  [`OracleHistoryMessage`]'s own validator.
	 */
	history?: OracleHistoryMessage[],
};

export type OracleAskResponse = {
	answer: string,
	context_type: string | null,
	context_id: string | null,
};

export type OracleContextPayload = {
	echo_id: string | null,
	shard_id: string | null,
	screen: string | null,
};

export type OracleContextResponse = {
	user_id: string,
	echo_count: number,
	echoes: OracleEchoRef[],
	shards: OracleShardRef[],
	recent_events: OracleEventRef[],
};

export type OracleEchoRef = {
	echo_id: string,
	name: string,
	status: string,
	current_shard_id: string,
	current_mood: string,
	avatar_url: string | null,
};

export type OracleEventRef = {
	item_id: string,
	echo_id: string,
	headline: string,
	tick_id: number,
	created_at: string,
};

// A prior message in the Oracle conversation for session continuity.
export type OracleHistoryMessage = {
	role: string,
	text: string,
};

export type OracleShardRef = {
	shard_id: string,
	name: string,
	status: string,
};

/**
 *  Orpheus-TTS preset voice identifier. The 8 voices ship in the
 *  canopyai/Orpheus-TTS 3B model. Wire format is snake_case to match
 *  the prompt prefix the model was trained on (e.g. `tara: <text>`).
 * 
 *  See `docs/observations/orpheus-voice-characterization-2026-04-17.md`
 *  for archetype mappings used by the persona→voice classifier.
 */
export type OrpheusVoice = "tara" | "leah" | "jess" | "leo" | "dan" | "mia" | "zac" | "zoe";

/**
 *  Shared pagination query parameters. Handlers can flatten this via
 *  `#[serde(flatten)]` into their own `Query` struct when they need
 *  additional filters.
 */
export type PageParams = {
	cursor?: string | null,
	limit?: number | null,
};

export type PasswordResetConfirmRequest = {
	reset_token: string,
	new_password: string,
};

export type PasswordResetRequest = {
	email: string,
};

export type PasswordResetResponse = {
	message: string,
};

export type PaymentRecord = {
	payment_id: string,
	user_id: string,
	payment_type: PaymentType,
	// Provider name: "nowpayments", "xaman", "stripe".
	provider: string,
	// Provider's reference ID for this payment.
	provider_payment_id: string,
	amount_usd_cents: number,
	// What the user actually paid in (e.g., "BTC", "XRP", "USD").
	currency: string,
	// Actual crypto amount paid (string to avoid float).
	crypto_amount?: string | null,
	status: PaymentStatus,
	description: string,
	created_at: string,
	confirmed_at: string | null,
};

export type PaymentStatus = "Pending" | "Confirming" | "Confirmed" | "Finished" | "Failed" | "Refunded" | "Expired";

export type PaymentType = "Subscription" | "MarketplacePurchase" | "Tip";

/**
 *  Per-shard decision in a DowngradeSession.
 * 
 *  `Undecided` is the initial state for every shard that loses its
 *  Included slot — the user must transition each to a terminal
 *  decision before the session can commit. On timeout, all remaining
 *  `Undecided` + `UpgradeBack` shards fall to `Archive` (conservative
 *  default that preserves content for 30 days).
 * 
 *  `UpgradeBack` per Flag B resolution (Session 100 dispatch): the
 *  shard stays `Included` in the DB during the 24-hour grace window
 *  so the user can complete a Stripe re-upgrade to restore their
 *  entitlement. If they don't re-upgrade in time, the timeout
 *  enforcer downgrades it to `Archive`.
 */
export type PendingDecision = "Undecided" | "BuyAddon" | "UpgradeBack" | "Archive";

/**
 *  View of a single shard's pending decision inside a DowngradeSession
 *  response. `Undecided` initial state; transitions via
 *  `POST /shard-decision`.
 */
export type PendingDecisionEntry = {
	shard_id: string,
	decision: string,
};

export type PersonaConsent = {
	consent_id: string,
	user_id: string,
	echo_id: string,
	consent_declaration: boolean,
	declaration_timestamp: string,
	is_self: boolean,
};

export type PersonaMode = "Quick" | "Detailed";

export type PickIncludedShardRequest = {
	session_id: string,
	shard_id: string,
};

export type PollVoteRequest = {
	discord_message_id: string,
	discord_channel_id: string,
	answer_id: number,
};

export type PostMessageRequest = {
	content: string,
};

export type ProfileVisibility = "Public" | "FriendsOnly" | "Private";

/**
 *  Provenance of a `PromotionalSubscription`. Reference: ME-MIS-001 §7.2.
 * 
 *  - `ClosedBetaReward` — 3-month God Mode grant for closed beta testers.
 *  - `OpenBetaReward` — 1-month Core grant for open beta testers.
 *  - `Custom` — discretionary grant (partnerships, support make-goods,
 *    etc). Tier + duration set by the granting admin; fields are not
 *    constrained by the two beta-reward shapes.
 */
export type PromoType = "ClosedBetaReward" | "OpenBetaReward" | "Custom";

/**
 *  A promotional subscription override. When an instance is active
 *  (`starts_at <= now < expires_at`) it takes precedence over the
 *  user's paid subscription tier for its duration.
 * 
 *  Primary key: `promo_id`. A user can have many records over time;
 *  query by `user_id` returns a list.
 */
export type PromotionalSubscription = {
	promo_id: string,
	user_id: string,
	promo_type: PromoType,
	granted_tier: GrantedTier,
	/**
	 *  UTC timestamp when the grant activates. For beta rewards this is
	 *  `public_launch_date`; for Custom it's whatever the operator set.
	 */
	starts_at: string,
	/**
	 *  UTC timestamp when the grant expires. The expiry enforcer
	 *  (`me_billing::subscription`) downgrades `User.subscription_tier`
	 *  to `auto_downgrade_to` at or after this time.
	 */
	expires_at: string,
	auto_downgrade_to: AutoDowngradeTier,
	created_at: string,
};

/**
 *  How a Private Shard was provisioned to its owner (ME-TIER-001 v6 §2).
 * 
 *  - `Included` — granted by tier (Creator=1, GodMode=3).
 *  - `PaidAddon` — purchased via the Private Shard add-on ($4.99/mo).
 *  - `Archived` — lost its Included slot on downgrade; 30-day retention
 *    window gated by `Shard.archive_expires_at`, then swept. During the
 *    window auto-restores on re-upgrade or add-on purchase (Commit 7B).
 * 
 *  For non-Private shards the field is a legacy no-op carrier — it is
 *  always populated (default `PaidAddon`) but ignored by business logic.
 */
export type ProvisioningType = "Included" | 
/**
 *  Migration default for pre-Commit-7 shards deserialised with no
 *  `provisioning_type`: treat as PaidAddon (they were manually
 *  created before included-shard semantics existed). The next
 *  subscription webhook re-classifies them to Included if the
 *  owner's tier entitles it.
 */
"PaidAddon" | "Archived";

export type PublicEchoRef = {
	echo_id: string,
	name: string,
	current_shard_id: string,
	current_mood: string,
	avatar_url: string | null,
	created_at: string,
	/**
	 *  True iff this Echo's owning user owns the Founding Echo badge.
	 *  Computed at response serialization via
	 *  `UserInventoryRepository::get_founding_echo_owners`. See
	 *  ME-MIS-001 §7.3.
	 */
	owner_is_founding_echo: boolean,
};

export type PublicProfileResponse = {
	user_id: string,
	display_name: string,
	bio: string | null,
	avatar_url: string | null,
	profile_visibility: ProfileVisibility,
	account_type: AccountType,
	subscription_tier: SubscriptionTier,
	created_at: string,
	// True iff the viewer and target mutually follow each other.
	mutual_follow: boolean,
	/**
	 *  True iff this user owns the Founding Echo badge in
	 *  `UserInventory`. Computed at response serialization via
	 *  `UserInventoryRepository::get_founding_echo_owners`. See
	 *  ME-MIS-001 §7.3.
	 */
	is_founding_echo: boolean,
};

export type PurchaseRequest = {
	item_id: string,
};

export type RelationshipResponse = {
	relationship_id: string,
	source_user_id: string,
	target_user_id: string,
	relationship_type: UserRelationshipType,
	created_at: string,
};

export type RelationshipStatus = "Active" | "Faded" | "Ended" | "Severed";

export type ReportResponse = {
	report_id: string,
	reporter_user_id: string,
	target_type: ReportTargetType,
	target_id: string,
	reason: string,
	details: string,
	status: ReportStatus,
	priority: number,
	created_at: string,
	resolved_at: string | null,
	resolution: string | null,
};

export type ReportStatus = "Pending" | "Reviewing" | "Resolved" | "Dismissed";

export type ReportTargetType = "Echo" | "User" | "Content" | "Message";

export type ResolveEscalationRequest = {
	resolution_notes: string,
};

export type SearchQuery = {
	q: string,
	cursor?: string | null,
	limit: number,
	/**
	 *  Legacy offset — accepted for back-compat with clients that haven't
	 *  migrated to cursor pagination yet. Ignored if `cursor` is set.
	 */
	offset?: number,
};

export type SearchResult = {
	item_type: string,
	item_id: string,
	echo_id: string | null,
	snippet: string,
	created_at: string,
	/**
	 *  True iff the owning user of the referenced content owns the
	 *  Founding Echo badge. For echo / diary / event rows the owner
	 *  is the caller (search is currently self-scoped — see
	 *  `list_by_owner(&auth.user_id)` in every handler). For shard
	 *  rows the field is always `false` — shard results do not
	 *  render a user badge (shards have no single owner).
	 *  Computed once per response from one batched
	 *  `UserInventoryRepository::get_founding_echo_owners` call.
	 *  Reference: ME-MIS-001 §7.3.
	 */
	owner_is_founding_echo: boolean,
};

export type SendMessageRequest = {
	content: string,
};

export type Shard = {
	shard_id: string,
	name: string,
	name_slug: string,
	shard_type: ShardType,
	owner_id: string | null,
	created_at: string,
	status: ShardStatus,
	tick_rate_modifier: number,
	max_active_echoes: number,
	max_hibernated_echoes: number,
	current_active_count: number,
	current_hibernated_count: number,
	allows_travel: boolean,
	allows_global_events: boolean,
	description: string,
	era: string,
	region: string,
	tags: string[],
	// Total events generated in this Shard (reputation metric, ME-SDB-001 §9.2).
	total_events_generated?: number,
	// URL of the AI-generated banner image (landscape). Null if generation pending/failed.
	banner_image?: string | null,
	/**
	 *  How this Private Shard was provisioned (ME-TIER-001 v6 §2).
	 *  Non-Private shards carry this field as `PaidAddon` by default and
	 *  ignore it. Pre-Commit-7 records deserialise with `PaidAddon` via
	 *  Default::default — see [`ProvisioningType::default`].
	 */
	provisioning_type?: ProvisioningType,
	/**
	 *  UTC instant the shard entered the Archived provisioning state.
	 *  `None` for every shard whose `provisioning_type != Archived`.
	 *  Set at the moment a downgrade choice selects Archive for this
	 *  shard (Commit 7B).
	 */
	archived_at?: string | null,
	/**
	 *  UTC instant at which the archive sweep deletes this shard.
	 *  Convention: `archived_at + 30 days`. The sweep
	 *  (`spawn_shard_archive_enforcer`) runs hourly and deletes shards
	 *  whose `archive_expires_at` is in the past. If the user upgrades
	 *  or purchases the Private Shard add-on during the window, both
	 *  `archived_at` and `archive_expires_at` are cleared (Commit 7B).
	 */
	archive_expires_at?: string | null,
	updated_at: string,
};

export type ShardDecisionRequest = {
	session_id: string,
	shard_id: string,
	/**
	 *  `"BuyAddon"` / `"UpgradeBack"` / `"Archive"`. `"Undecided"` is
	 *  the initial state and is rejected here — user must pick one
	 *  of the three terminal decisions.
	 */
	decision: string,
};

export type ShardDetail = {
	shard_id: string,
	name: string,
	shard_type: string,
	status: string,
	description: string,
	era: string,
	region: string,
	tags: string[],
	current_active_count: number,
	current_hibernated_count: number,
	max_active_echoes: number,
	max_hibernated_echoes: number,
	allows_travel: boolean,
	tick_rate_modifier: number,
	banner_image: string | null,
	created_at: string,
	// Locale of name/description fields: user's locale or "en" (pending).
	content_locale: string,
	/**
	 *  How this shard was provisioned (ME-TIER-001 v6 §2). See
	 *  [`ShardSummary::provisioning_type`] for the rendering contract.
	 */
	provisioning_type: ProvisioningType,
	/**
	 *  UTC instant this shard entered the Archived state. See
	 *  [`ShardSummary::archived_at`] for the rendering contract.
	 */
	archived_at: string | null,
	/**
	 *  UTC instant at which the archive sweep deletes this shard. See
	 *  [`ShardSummary::archive_expires_at`] for the rendering contract.
	 */
	archive_expires_at: string | null,
};

export type ShardEchoSummary = {
	echo_id: string,
	name: string,
	status: string,
	current_mood: string,
	current_location_id: string,
	current_tick: number,
};

export type ShardListQuery = {
	// Filter by shard type: `public` or `private`.
	type: string | null,
	// Comma-separated tag filter.
	tags: string | null,
	// Sort order: `population` or `newest` (default).
	sort: string,
};

export type ShardLocation = {
	location_id: string,
	shard_id: string,
	name: string,
	location_type: LocationType,
	description: string,
	capacity: number,
	connects_to: string[],
	travel_time_ticks: number,
	is_spawn_point: boolean,
	social_density: number,
	economic_activity: number,
	danger_level: number,
};

export type ShardPlacement = {
	echo_id: string,
	shard_id: string,
	location_id: string,
	arrived_at_tick: number,
	travel_state: TravelState,
	destination_id: string | null,
	arrival_tick: number | null,
};

export type ShardStatus = "Active" | "Paused" | "Archived" | "PendingDeletion";

export type ShardSummary = {
	shard_id: string,
	name: string,
	shard_type: string,
	status: string,
	description: string,
	current_active_count: number,
	current_hibernated_count: number,
	max_active_echoes: number,
	banner_image: string | null,
	created_at: string,
	// Locale of name/description fields: user's locale or "en" (pending).
	content_locale: string,
	/**
	 *  How this shard was provisioned (ME-TIER-001 v6 §2). Drives the
	 *  archived-shard card banner in ME-MIS-001 §5.2. Mirrors
	 *  `Shard.provisioning_type`.
	 */
	provisioning_type: ProvisioningType,
	/**
	 *  UTC instant this shard entered the Archived state. `None` unless
	 *  `provisioning_type == Archived`. Drives the ME-MIS-001 §5.2
	 *  archived-shard banner timestamp. Mirrors `Shard.archived_at`.
	 */
	archived_at: string | null,
	/**
	 *  UTC instant at which the archive sweep deletes this shard
	 *  (convention: `archived_at + 30 days`). Drives the ME-MIS-001
	 *  §5.2 countdown label on archived-shard cards and the
	 *  Account → Subscription pending-deletion list. Mirrors
	 *  `Shard.archive_expires_at`.
	 */
	archive_expires_at: string | null,
};

export type ShardTheme = {
	theme_id: string,
	shard_id: string,
	setting_prompt: string,
	cultural_norms: string,
	economic_model: EconomicModel,
	technology_level: TechnologyLevel,
	conflict_style: ConflictStyle,
	available_occupations: string[],
	banned_elements: string[],
	custom_rules: string,
	shard_prompt_template: string | null,
	/**
	 *  Proper-noun-free visual description for image prompt generation.
	 *  Colors, lighting, composition, atmosphere, textures — no names, dates, or places.
	 */
	visual_style?: string | null,
	/**
	 *  Starting wealth for Echoes entering this Shard (fixed-point).
	 *  Default: 1000 (1.0 in fixed-point).
	 */
	starting_wealth: number,
};

export type ShardType = "Public" | "Private" | "Personal";

/**
 *  Off-platform social handle surfaced on the public profile.
 * 
 *  `platform` is a short identifier (e.g. "twitter", "github", "mastodon")
 *  validated against the platform allowlist at write time. `url` is the
 *  full URL (scheme + host allowlist enforced). Stored as a flat Vec on
 *  `User` rather than a side table — the set is small (O(5)) and always
 *  read with the user row.
 */
export type SocialLink = {
	platform: string,
	url: string,
};

// Story export job for Echo timeline rendering. Reference: ME-UAD-001 §5.4.
export type StoryExport = {
	export_id: string,
	user_id: string,
	// Selected Echo IDs to export (one or more).
	echo_ids: string[],
	format: ExportFormat,
	status: ExportStatus,
	created_at: string,
	completed_at: string | null,
	download_path: string | null,
	// Subtitle file path for video exports.
	subtitle_path: string | null,
	// Optional date range filter (inclusive start).
	from_date: string | null,
	// Optional date range filter (inclusive end).
	to_date: string | null,
};

// Request body for story export.
export type StoryExportRequest = {
	// One or more Echo IDs to export.
	echo_ids: string[],
	format: ExportFormat,
	// Optional date range filter (ISO date, e.g. "2026-01-15").
	from_date: string | null,
	// Optional date range filter (ISO date, e.g. "2026-04-01").
	to_date: string | null,
};

// Response for story export.
export type StoryExportResponse = {
	export_id: string,
	format: string,
	status: string,
	created_at: string,
	download_path: string | null,
	subtitle_path: string | null,
};

export type SubmitFeedbackRequest = {
	user_message: string,
	structured_summary: string,
	feedback_type: FeedbackType,
	context: FeedbackContext,
};

export type SubmitFeedbackResponse = {
	feedback_id: string,
	status: string,
	message: string,
};

export type SubscriptionStatus = "Active" | "PastDue" | "Cancelled" | "Expired";

export type SubscriptionTier = "Free" | "Starter" | "Core" | "Creator" | "GodMode";

export type SystemStatusResponse = {
	tick_number: number,
	tick_duration_ms: number,
	ram_usage_mb: number,
	vram_usage_mb: number,
	vram_total_mb: number,
	active_echoes: number,
	hibernated_echoes: number,
	total_users: number,
	total_shards: number,
};

export type TechnologyLevel = "Primitive" | "Industrial" | "Modern" | "NearFuture" | "FarFuture" | "Fantasy";

export type TickResponse = {
	message: string,
	tick_id: number,
};

export type TickStateResponse = {
	tick_number: number,
	tick_duration_ms: number,
	paused: boolean,
};

export type TravelRequest = {
	destination_shard_id: string,
};

export type TravelRequestDecision = {
	approved: boolean,
};

export type TravelRequestResponse = {
	request_id: string,
	echo_id: string,
	requester_user_id: string,
	destination_shard_id: string,
	status: string,
	created_at: string,
	expires_at: string,
};

export type TravelResponse = {
	status: string,
	arrival_tick: number | null,
	request_id: string | null,
	expires_at: string | null,
};

export type TravelState = "Stationary" | "Travelling";

export type UpdateAccountRequest = {
	display_name: string | null,
	email: string | null,
	locale: string | null,
	timezone: string | null,
};

export type UpdateBreachRecordRequest = {
	notified_authorities: boolean | null,
	notified_users: boolean | null,
	resolved: boolean | null,
};

export type UpdateCSAMIncidentRequest = {
	ncmec_report_id: string | null,
	regional_report_id: string | null,
	/**
	 *  Status transition. Any variant is accepted; `Closed {
	 *  reason: FalsePositive }` additionally reverses enforcement.
	 */
	status: CSAMIncidentStatus | null,
	preservation_locked: boolean | null,
	notes: string | null,
};

export type UpdateChannelRequest = {
	description: string | null,
	is_read_only: boolean | null,
	slow_mode_seconds: number | null,
	status: ChannelStatus | null,
};

export type UpdateDiscordPrefsRequest = {
	sync_display_name: boolean | null,
};

export type UpdatePreferencesRequest = {
	echo_life_events: NotificationDelivery | null,
	daily_digest: NotificationDelivery | null,
	social: NotificationDelivery | null,
	community: NotificationDelivery | null,
	shard_activity: NotificationDelivery | null,
	platform: NotificationDelivery | null,
	marketplace: NotificationDelivery | null,
	billing: NotificationDelivery | null,
	moderation: NotificationDelivery | null,
	account: NotificationDelivery | null,
};

export type UpdatePrivacyRequest = {
	solo_mode: boolean | null,
	do_not_sell: boolean | null,
	profile_visibility: ProfileVisibility | null,
};

export type UpdateProfileRequest = {
	display_name: string | null,
	/**
	 *  User's UI locale. Must be `"en"` or one of `config.translation.supported_locales`.
	 *  Reference: docs/claude/i18n-multilingual-tasks.md CC TASK 1 STEP 6.
	 */
	locale: string | null,
	// Free-text bio shown on the public profile. Empty string clears it.
	bio: string | null,
};

export type UpdateReportRequest = {
	status: ReportStatus | null,
	priority: number | null,
	resolution: string | null,
};

export type UpdateShardRequest = {
	name: string | null,
	description: string | null,
	status: string | null,
};

export type User = {
	user_id: string,
	/**
	 *  Email address. At rest in Redb this field holds AES-256-GCM
	 *  ciphertext whenever `email_encrypted == true`; API responses always
	 *  emit plaintext because the repository decrypts on read. The `email`
	 *  JSON key itself is unchanged across the wire for client-side
	 *  compatibility. Reference: ME-UAD-001 §9.1, ME-PDP-001 §6.1.
	 */
	email: string,
	email_verified: boolean,
	display_name: string,
	display_name_slug: string,
	account_type: AccountType,
	subscription_tier: SubscriptionTier,
	created_at: string,
	updated_at: string,
	last_login_at: string,
	account_status: AccountStatus,
	locale: string,
	timezone: string | null,
	onboarding_complete: boolean,
	tos_accepted_at: string,
	tos_version: string,
	privacy_accepted_at: string,
	privacy_version: string,
	/**
	 *  Echo count limit override. 0 = use tier default from config.
	 *  Non-zero = hard override (e.g., admin grant, beta reward).
	 *  Reference: ME-UAD-001 §6.1.
	 */
	echo_count_limit?: number,
	/**
	 *  When true, this user's Echoes never interact with other users' Echoes.
	 *  Reference: ME-PDP-001 (cross-user consent), ME-UAD-001 §4.
	 */
	solo_mode?: boolean,
	/**
	 *  When set, account will be purged after this date (30-day grace period).
	 *  Reference: ME-PDP-001 §5.3, ME-UAD-001 §5.1.
	 */
	deletion_scheduled_at?: string | null,
	/**
	 *  CCPA "Do Not Sell My Personal Information" flag.
	 *  When true, analytics_opt_out is also true.
	 *  Reference: ME-PDP-001 §4.3.
	 */
	do_not_sell?: boolean,
	/**
	 *  When true, client-side analytics events are discarded.
	 *  Linked to do_not_sell per ME-PDP-001.
	 */
	analytics_opt_out?: boolean,
	/**
	 *  GDPR Art. 18 — Right to Restriction of Processing. When true, the
	 *  tick engine MUST skip every Echo owned by this user — no diary
	 *  generation, no relationship updates, no LLM calls. Distinct from
	 *  `solo_mode` (which only blocks cross-user interaction) and from
	 *  account deletion (data is preserved). Toggled via
	 *  POST /account/me/restrict-processing  +  /unrestrict-processing.
	 */
	processing_restricted?: boolean,
	/**
	 *  When the current paid subscription expires. None = Free tier (no expiry).
	 *  Crypto payments set this to `now + duration_days`. Extension adds to existing.
	 */
	subscription_expires_at?: string | null,
	// Stripe customer ID (cus_...). Populated on first Stripe checkout.
	stripe_customer_id?: string | null,
	// Stripe subscription ID (sub_...). Populated on checkout.session.completed.
	stripe_subscription_id?: string | null,
	/**
	 *  Public profile visibility — controls what other authenticated users see
	 *  at `GET /users/{user_id}`. Default `Public` on deserialisation for
	 *  accounts that predate this field. Reference: ME-API-001 §4.3.3.
	 */
	profile_visibility: ProfileVisibility,
	// Free-text bio surfaced on the public profile (max 500 chars).
	bio?: string | null,
	/**
	 *  Public avatar URL returned on profile and list endpoints. Populated by
	 *  `POST /account/me/profile/avatar`. None = default placeholder on client.
	 */
	avatar_url?: string | null,
	/**
	 *  Off-platform social links surfaced on the public profile. Each link
	 *  is validated at write time (scheme + host allowlist per
	 *  ME-UAD-001 §2.3). Empty vec for accounts that predate this field.
	 */
	social_links?: SocialLink[],
	/**
	 *  Opt-in flag controlling whether other authenticated users can
	 *  discover this user's Echo stories via the public feed. Defaults to
	 *  `false` — public visibility is opt-in, not opt-out, per the
	 *  platform's privacy-by-default posture. Reference: ME-UAD-001 §2.3.
	 */
	public_echo_feed?: boolean,
};

export type UserInventory = {
	inventory_id: string,
	user_id: string,
	item_id: string,
	equipped: boolean,
	equipped_target_id: string | null,
	acquired_at: string,
};

export type UserPurchase = {
	purchase_id: string,
	user_id: string,
	item_id: string,
	price_paid_cents: number,
	purchased_at: string,
	payment_reference: string,
};

export type UserRelationship = {
	relationship_id: string,
	source_user_id: string,
	target_user_id: string,
	relationship_type: UserRelationshipType,
	created_at: string,
};

export type UserRelationshipType = "Follow" | "Block" | "Mute";

export type UserReport = {
	report_id: string,
	reporter_user_id: string,
	target_type: ReportTargetType,
	target_id: string,
	reason: string,
	details?: string,
	status: ReportStatus,
	// Priority: 0 = P0 (imminent harm), 1 = P1, 2 = P2, 3 = P3 (lowest).
	priority: number,
	created_at: string,
	resolved_at: string | null,
	resolution: string | null,
};

export type UserSession = {
	session_id: string,
	user_id: string,
	refresh_token_hash: string,
	device_fingerprint: string | null,
	created_at: string,
	expires_at: string,
	last_used_at: string,
	revoked: boolean,
};

export type UserSubscription = {
	user_id: string,
	tier: SubscriptionTier,
	status: SubscriptionStatus,
	started_at: string,
	current_period_end: string,
	payment_provider_id: string | null,
	echo_count_limit: number,
	/**
	 *  Daily Influence Points cap. `None` for uncapped tiers (GodMode);
	 *  `Some(n)` for finite caps. Session 099 Commit 3.5 aligned this
	 *  field with `AppConfig::influence_daily_limit` to retire the
	 *  `u32::MAX` unlimited sentinel end-to-end across every type
	 *  specta exports.
	 */
	influence_points_daily: number | null,
	updated_at: string,
};

export type VersionResponse = {
	version: string,
	name: string,
};

// A complete voice conversation session between a user and their Echo.
export type VoiceConversation = {
	id: string,
	echo_id: string,
	user_id: string,
	transcript: VoiceConversationTurn[],
	started_at: string,
	ended_at: string | null,
	/**
	 *  LLM-generated summary of the conversation (2-3 sentences).
	 *  Injected into tick prompts and future voice call context.
	 */
	summary: string | null,
};

// A single turn in a voice conversation.
export type VoiceConversationTurn = {
	speaker: string,
	text: string,
	timestamp: string,
};

/**
 *  One turn of a persisted voice conversation. Mirrors
 *  `me_core::models::voice::VoiceConversationTurn` with `utoipa::ToSchema`
 *  AND `specta::Type` so both the OpenAPI spec and the generated
 *  TypeScript client types carry a concrete type instead of a generic
 *  `Object`.
 */
export type VoiceConversationTurnView = {
	// `"user"` or `"echo"`.
	speaker: string,
	text: string,
	// ISO 8601 / RFC 3339 timestamp.
	timestamp: string,
};

/**
 *  One row returned by `GET /echoes/{id}/voice/history`. Mirrors
 *  `me_core::models::voice::VoiceConversation`, converting the
 *  `DateTime<Utc>` columns to RFC 3339 strings for wire stability.
 */
export type VoiceConversationView = {
	id: string,
	echo_id: string,
	user_id: string,
	transcript: VoiceConversationTurnView[],
	// RFC 3339 start timestamp.
	started_at: string,
	// RFC 3339 end timestamp; `None` for sessions that haven't ended yet.
	ended_at: string | null,
	/**
	 *  LLM-generated summary when the session ended. `None` while the
	 *  session is still in progress or the summariser hasn't caught up.
	 */
	summary: string | null,
};

export type VoiceSessionResponse = {
	active: boolean,
	echo_id: string | null,
	voice_ws_url: string | null,
	started_at: string | null,
	remaining_seconds?: number | null,
};

export type VoiceStartResponse = {
	voice_ws_url: string,
	echo_id: string,
	session_nonce: number,
	conversation_id: string,
	session_duration_seconds: number,
	/**
	 *  Cloudflare Calls App ID for WebRTC audio transport.
	 *  Client uses this to configure STUN/TURN. Secret stays server-side.
	 */
	calls_app_id: string,
	/**
	 *  Short-lived, single-use token embedded in `voice_ws_url`. The
	 *  pipeline sidecar verifies this via the loopback-only endpoint
	 *  /internal/voice/verify-session before accepting the WS upgrade.
	 *  Clients don't need to use this value directly — it's already
	 *  baked into `voice_ws_url` — but it's returned here so a custom
	 *  client could validate the URL it received.
	 */
	session_token: string,
};

export type WaitlistCountResponse = {
	count: number,
};

// Waitlist entry for pre-launch signups. Reference: ME-UXF-001 §4.1.
export type WaitlistEntry = {
	entry_id: string,
	/**
	 *  Email address. At rest in Redb this field holds AES-256-GCM
	 *  ciphertext whenever `email_encrypted == true`; API responses
	 *  always emit plaintext because the repository decrypts on read.
	 *  Reference: ME-UAD-001 §9.1, ME-PDP-001 §6.1.
	 */
	email: string,
	// Queue position (auto-incremented, adjusted by referrals).
	position: number,
	// Unique referral code for this entry.
	referral_code: string,
	// entry_id of the user who referred this signup.
	referred_by: string | null,
	// UTM source tracking.
	source: string | null,
	status: WaitlistStatus,
	created_at: string,
	invited_at: string | null,
};

export type WaitlistPositionResponse = {
	entry_id: string,
	position: number,
	status: string,
	referral_code: string,
	referral_count: number,
};

export type WaitlistSignupRequest = {
	email: string,
	// Optional referral code from an existing waitlist member.
	referral_code: string | null,
	// UTM source tracking.
	source: string | null,
};

export type WaitlistSignupResponse = {
	entry_id: string,
	position: number,
	referral_code: string,
};

// Status of a waitlist entry. Reference: ME-UXF-001 §4.1.
export type WaitlistStatus = "Waiting" | "Invited" | "Registered" | "Declined";

// Envelope for all world events.
export type WorldEvent = {
	event_id: string,
	tick_id: number,
	timestamp: string,
	payload: WorldEventPayload,
};

// All event variants from the doc suite.
export type WorldEventPayload = { EchoCreated: { echo_id: string; owner_id: string } } | { EchoDeleted: { echo_id: string } } | { EchoHibernated: { echo_id: string; reason: string } } | { EchoWoken: { echo_id: string } } | 
// Emitted when a quarantined Echo is restored by admin. Phase 7.
{ EchoRestored: { echo_id: string } } | { TickStarted: { tick_id: number } } | { TickCompleted: { tick_id: number } } | { DiaryEntryGenerated: { echo_id: string; diary_id: string } } | { DiaryImageReady: { echo_id: string; diary_id: string; image_url: string } } | { LifeEventOccurred: { echo_id: string; event_id: string } } | { MoodChanged: { echo_id: string; old_mood: string; new_mood: string } } | { EchoInteraction: { echo_a: string; echo_b: string; interaction_type: string; tick_id: number } } | 
// Emitted from process_interaction_with_analytics when a new Echo relationship forms.
{ RelationshipFormed: { echo_a: string; echo_b: string } } | 
// Emitted when an existing Echo relationship changes type. Phase 7.
{ RelationshipChanged: { echo_a: string; echo_b: string } } | { ShardCreated: { shard_id: string; shard_type: string; owner_id: string } } | { ShardStatusChanged: { shard_id: string; old_status: string; new_status: string } } | { ShardTravelRequested: { echo_id: string; from_shard: string; to_shard: string } } | { ShardTravelApproved: { echo_id: string; destination_shard: string } } | { ShardTravelCompleted: { echo_id: string; shard_id: string } } | { ShardTravelDenied: { echo_id: string; reason: string } } | { ShardCapacityWarning: { shard_id: string; percent: number } } | { EchoMoved: { echo_id: string; shard_id: string; from_location: string; to_location: string; arrival_tick: number } } | { EchoWealthChanged: { echo_id: string; old_value: number; new_value: number; reason: string } } | { GlobalEventPropagated: { event_id: string; affected_shards: string[] } } | 
// Emitted by safety classifier on T2/T3 detection. Wired via record_content_flagged().
{ ContentFlagged: { content_id: string; tier: string } } | 
// Emitted when T3 content triggers Echo quarantine. Phase 7 safety enforcement.
{ EchoQuarantined: { echo_id: string; reason: string } } | 
// Phase 7 — emergent behavior detection.
{ EmergentGroupFlagged: { echo_ids: string[] } } | { InfluencePointUsed: { user_id: string; echo_id: string; points: number } } | { UserRegistered: { user_id: string } } | 
// Emitted by purge_user() after full data cascade. Requires EventBus in PurgeContext (Phase 7).
{ UserDeleted: { user_id: string } } | { PersonaUpdated: { echo_id: string; version: number } } | { ConversationSaved: { echo_id: string; user_id: string } } | 
// Phase 7 — user feedback system.
{ FeedbackSubmitted: { user_id: string; feedback_id: string } } | { CommunityMessagePosted: { channel_id: string; message_id: string; author_id: string } } | { MessageDeleted: { channel_id: string; message_id: string; deleted_by: string } } | { MessageEdited: { channel_id: string; message_id: string; author_id: string } } | { FeedItemGenerated: { feed_item_id: string; echo_id: string; shard_id: string } } | { UserFollowed: { source_user_id: string; target_user_id: string } } | { UserBlocked: { source_user_id: string; target_user_id: string } } | { UserMuted: { source_user_id: string; target_user_id: string } } | 
/**
 *  An Admin changed a user's `AccountType` (ME-CSS-001 §9.1
 *  Moderator role management). Emitted by
 *  `POST /admin/moderators/:id/promote` and
 *  `DELETE /admin/moderators/:id`. `actor_id` is the admin who
 *  performed the change; `user_id` is the target.
 */
{ UserAccountTypeChanged: { user_id: string; from: AccountType; to: AccountType; actor_id: string } } | { NotificationCreated: { user_id: string; notification_id: string } } | 
// Emitted when the daily digest notification is generated. Phase 7 digest system.
{ DailyDigestGenerated: { user_id: string; notification_id: string } } | 
// Emitted when an Echo's AI-generated portrait is ready (background generation complete).
{ EchoAvatarReady: { echo_id: string; avatar_url: string } } | { EmergencyHibernation: { reason: string } } | 
/**
 *  A user's active `PromotionalSubscription` is approaching expiry.
 *  Emitted by the hourly `SubscriptionExpiryEnforcer` at 30, 7, and
 *  1 day remaining. Deduplicated via `PromotionalSubscription.notified_thresholds`
 *  so each threshold fires exactly once per promo. Consumers: the
 *  notification-creation path (not wired in Block 3 — see debt.md
 *  entry "Pre-expiry PromotionalSubscription notification UI").
 *  Reference: ME-MIS-001 §7.2, §12.4.
 */
{ PromotionalSubscriptionExpiring: { user_id: string; days_remaining: number } } | 
/**
 *  Audit event: the daily `DataLifecycleEnforcer` just purged
 *  hibernated Echoes and/or archived Private Shards that crossed
 *  their 90-day grace window (ME-MIS-001 §5.2).
 * 
 *  One event per user per sweep pass.
 */
{ HibernatedContentDeleted: { user_id: string; echo_ids: string[]; shard_ids: string[]; deleted_at: string } };

// Query params for WebSocket connection (JWT token).
export type WsAuthQuery = {
	/**
	 *  Short-lived JWT access token. Browsers can't set
	 *  `Authorization` headers during the WebSocket upgrade handshake,
	 *  so the token is passed in the query string. The server
	 *  validates signature + expiry + blocklist on every upgrade.
	 */
	token: string | null,
};

/**
 *  Events sent over the WebSocket to clients.
 * 
 *  All frames delivered on any `/ws/*\/stream` endpoint — EXCEPT the
 *  initial handshake frame and (for the shard stream) the raw
 *  [`WsShardWorldEventFrame`] envelope — are JSON-encoded values of
 *  this tagged union. The `type` field is the discriminator.
 */
export type WsEchoEvent = { type: "DiaryEntryCreated"; echo_id: string; diary_id: string; tick_id: number; 
/**
 *  Locale hint for the just-persisted content. Resolved per-event
 *  via a non-blocking lookup against `ContentTranslationRepository`:
 *  if a translation row already exists for the connected user's
 *  locale (e.g. from startup catchup or backfill), this carries
 *  that locale; otherwise `"en"`. Clients still refetch via GET for
 *  the authoritative value. CC TASK 3 Step 4 + audit D1.
 */
content_locale: string } | { type: "DiaryImageReady"; echo_id: string; diary_id: string; image_url: string } | { type: "LifeEventOccurred"; echo_id: string; event_id: string; tick_id: number; 
// See `DiaryEntryCreated::content_locale`. CC TASK 3 Step 4.
content_locale: string } | { type: "MoodChanged"; echo_id: string; mood: string; tick_id: number } | { type: "EchoMoved"; echo_id: string; from_location: string; to_location: string } | { type: "PersonaUpdated"; echo_id: string; version: number } | { type: "EchoHibernated"; echo_id: string; reason: string } | { type: "EchoWoken"; echo_id: string } | { type: "EchoWealthChanged"; echo_id: string; old_value: number; new_value: number; reason: string } | { type: "EchoDeleted"; echo_id: string } | { type: "ShardTravelCompleted"; echo_id: string; shard_id: string } | { type: "ShardCreated"; shard_id: string; shard_type: string } | { type: "CommunityMessagePosted"; channel_id: string; message_id: string; author_id: string } | { type: "CommunityMessageEdited"; channel_id: string; message_id: string; author_id: string } | { type: "CommunityMessageDeleted"; channel_id: string; message_id: string; deleted_by: string } | { type: "NotificationCreated"; notification_id: string } | { type: "EchoAvatarReady"; echo_id: string; avatar_url: string } | { type: "Connected"; echo_id: string; message: string } | { type: "Error"; message: string };
