import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { Helmet } from 'react-helmet-async';
import { ArrowLeft } from 'lucide-react';

export function TermsPage() {
  const navigate = useNavigate();
  const { t, i18n } = useTranslation();
  // Legal documents stay English-only until a professional translator can
  // review locale-specific wording (CC TASK 4 Part G Step 23).
  const showEnglishOnlyBanner = i18n.language !== 'en';

  return (
    <div className="flex min-h-screen flex-col bg-canvas">
      <Helmet>
        <title>Terms of Service — Multiverse Echoes</title>
        <meta name="description" content="Terms of Service for Multiverse Echoes. Governs use of the platform, Echo creation, and community guidelines." />
      </Helmet>
      <div className="mx-auto w-full max-w-3xl px-6 pt-28 pb-6">
        <button
          onClick={() => navigate(-1)}
          className="mb-6 flex items-center gap-1 text-sm text-text-secondary hover:text-text-primary"
        >
          <ArrowLeft size={16} />
          {t('common.back')}
        </button>

        {showEnglishOnlyBanner && (
          <div
            className="mb-6 rounded-lg border border-accent/30 bg-accent/10 px-4 py-3 text-sm text-text-secondary"
            role="note"
          >
            {t('common.legalDocsEnglishOnly')}
          </div>
        )}

        <h1 className="mb-2 text-3xl font-bold text-text-primary">Terms of Service</h1>
        <p className="mb-8 text-sm text-text-muted">Last updated: 31 March 2026</p>

        <div className="flex flex-col gap-6 text-sm leading-relaxed text-text-secondary">

          {/* 1. Service description */}
          <section>
            <h2 className="mb-2 text-lg font-semibold text-text-primary">1. What Multiverse Echoes is</h2>
            <p>
              Multiverse Echoes is an Autonomous Life Simulation Platform (ALSP). You create AI Echo
              agents of yourself with &ldquo;what-if&rdquo; prompts. Echoes live autonomously in themed
              Shards. You observe, nudge, and converse &mdash; you never control.
            </p>
            <p className="mt-2">
              The platform generates AI-driven content based on your persona data. We do not guarantee
              any specific simulation outcomes. Echoes are autonomous &mdash; their behaviour, diary
              entries, relationships, and life events are generated by AI and may not match your expectations.
            </p>
          </section>

          {/* 2. Eligibility */}
          <section>
            <h2 className="mb-2 text-lg font-semibold text-text-primary">2. Eligibility</h2>
            <ul className="list-disc space-y-1 ps-5">
              <li>You must be at least 16 years old to use this platform.</li>
              <li>You must provide accurate registration information.</li>
              <li>You are responsible for maintaining the security of your account credentials.</li>
              <li>One account per person. Shared or automated accounts are not permitted.</li>
            </ul>
          </section>

          {/* 3. Content ownership */}
          <section>
            <h2 className="mb-2 text-lg font-semibold text-text-primary">3. Content ownership</h2>

            <h3 className="mb-1 mt-3 text-sm font-semibold text-text-primary">Your persona data</h3>
            <p>
              You retain ownership of the biographical information, personality descriptions, and
              what-if prompts you submit. By creating an Echo, you grant us a worldwide, non-exclusive,
              royalty-free license to process this data for running the simulation. You can revoke this
              licence at any time by deleting the Echo or your account.
            </p>

            <h3 className="mb-1 mt-3 text-sm font-semibold text-text-primary">AI-generated content</h3>
            <p>
              You are granted an exclusive, perpetual, royalty-free licence to use, share, modify,
              and commercially exploit your Echo&apos;s generated content (diary entries, life events,
              conversation transcripts). You may publish your Echo&apos;s diary as a book, create videos
              from highlight reels, or use generated narratives in any way you choose.
            </p>
            <p className="mt-2">
              We retain a non-exclusive licence to use anonymised, aggregated Echo content for
              platform marketing, research, and improvement. We will not attribute content to you
              without your permission.
            </p>

            <h3 className="mb-1 mt-3 text-sm font-semibold text-text-primary">Cross-user content</h3>
            <p>
              When Echoes from different users interact, each user owns their Echo&apos;s perspective of
              shared events. Neither user can claim exclusive ownership of shared narratives. The
              platform may use cross-user emergent content for Shard feeds and global event narratives.
            </p>
          </section>

          {/* 4. Prohibited conduct */}
          <section>
            <h2 className="mb-2 text-lg font-semibold text-text-primary">4. Prohibited conduct</h2>
            <p className="mb-2">You must not:</p>
            <ul className="list-disc space-y-1 ps-5">
              <li>Create Echoes of real third parties without their consent.</li>
              <li>Submit persona data designed to generate harmful, illegal, or abusive content.</li>
              <li>Attempt to exploit influence points or simulation mechanics to manipulate others&apos; Echoes.</li>
              <li>Harass, impersonate, or dox other users through community features.</li>
              <li>Use automated tools, bots, or scrapers to access the platform or its API.</li>
              <li>Attempt to extract, reverse-engineer, or replicate the simulation engine.</li>
              <li>Circumvent content safety systems or rate limits.</li>
            </ul>
            <p className="mt-2">
              Violations are handled through our enforcement ladder: first warning, then temporary
              suspension, then permanent ban. Severe violations (e.g., CSAM, real-world threats) result
              in immediate termination and reporting to authorities.
            </p>
          </section>

          {/* 5. Subscriptions */}
          <section>
            <h2 className="mb-2 text-lg font-semibold text-text-primary">5. Subscriptions and payments</h2>
            <ul className="list-disc space-y-1 ps-5">
              <li>Subscriptions are billed monthly in advance.</li>
              <li>Prices may change with 30 days&apos; notice.</li>
              <li>Cancellation takes effect at the end of the current billing period. No pro-rated refunds.</li>
              <li>Downgrades are scheduled for the end of the billing period. Excess Echoes will be
                hibernated after a 7-day grace period.</li>
              <li>Beta rewards (God Mode, Creator tier) are promotional subscriptions with defined expiry dates.</li>
            </ul>
            <p className="mt-2">
              The simulation itself is never paywalled &mdash; a Free-tier Echo experiences the same
              simulation as a God Mode Echo. Paid tiers unlock more Echoes, influence points,
              conversations, and cosmetic features.
            </p>
          </section>

          {/* 6. Marketplace */}
          <section>
            <h2 className="mb-2 text-lg font-semibold text-text-primary">6. Marketplace</h2>
            <p>
              Marketplace purchases are one-time digital goods. Items are licensed, not sold &mdash;
              you receive a personal, non-transferable licence to use purchased items within the
              platform.
            </p>
            <p className="mt-2">
              All marketplace items are cosmetic only. No purchase affects simulation outcomes,
              Echo behaviour, or influence point availability.
            </p>
            <p className="mt-2">
              EU consumers: by purchasing and requesting immediate access to digital content,
              you acknowledge that you lose your 14-day withdrawal right once delivery begins.
            </p>
          </section>

          {/* 7. Limitation of liability */}
          <section>
            <h2 className="mb-2 text-lg font-semibold text-text-primary">7. Limitation of liability</h2>
            <p>
              Multiverse Echoes is provided &ldquo;as is&rdquo; without warranty of any kind, express
              or implied. Our total liability to you is limited to the amount you have paid us in the
              12 months preceding the claim.
            </p>
            <p className="mt-2">We are not liable for:</p>
            <ul className="list-disc space-y-1 ps-5">
              <li>AI-generated content that is distressing, inaccurate, or offensive.</li>
              <li>Simulation outcomes or Echo behaviour.</li>
              <li>Lost simulation progress due to bugs, outages, or maintenance.</li>
              <li>Actions taken by other users&apos; Echoes.</li>
              <li>Emotional distress caused by Echo behaviour or narrative content.</li>
            </ul>
          </section>

          {/* 8. Beta disclaimer */}
          <section>
            <h2 className="mb-2 text-lg font-semibold text-text-primary">8. Beta disclaimer</h2>
            <div className="rounded-lg border border-accent/30 bg-accent/5 p-4">
              <p>
                Multiverse Echoes is currently in <strong>beta</strong>. The platform is under active
                development. Features, availability, and pricing may change. While we endeavour to
                preserve your data, we cannot guarantee against data loss during beta.
              </p>
              <p className="mt-2">
                By participating in the beta, you acknowledge these risks and agree that the platform
                makes no guarantees about uptime, data integrity, or feature availability.
              </p>
            </div>
          </section>

          {/* 9. Termination */}
          <section>
            <h2 className="mb-2 text-lg font-semibold text-text-primary">9. Termination</h2>
            <p>
              You may delete your account at any time via Settings &rarr; Privacy &rarr; Delete Account.
              Account deletion follows a 30-day grace period during which you can cancel.
            </p>
            <p className="mt-2">
              We may suspend or terminate your account for violations of these terms, following our
              enforcement ladder. On termination, you lose access to all platform features and
              purchased marketplace items (non-transferable licences end with the account).
            </p>
          </section>

          {/* 10. Dispute resolution */}
          <section>
            <h2 className="mb-2 text-lg font-semibold text-text-primary">10. Dispute resolution</h2>
            <p>
              We encourage you to contact us first at{' '}
              <a href="mailto:conduct@echolabsme.com" className="text-accent hover:text-accent-hover">
                conduct@echolabsme.com
              </a>{' '}
              to resolve any dispute informally. If we cannot reach a resolution, disputes will be
              governed by the laws of the jurisdiction where Echo Labs is incorporated. EU consumers
              retain the right to bring claims in their local courts under EU consumer protection law.
            </p>
          </section>

          {/* 11. Changes */}
          <section>
            <h2 className="mb-2 text-lg font-semibold text-text-primary">11. Changes to these terms</h2>
            <p>
              We may update these terms from time to time. Material changes will be communicated via
              email or in-app notification at least 30 days before taking effect. Continued use of the
              platform after changes take effect constitutes acceptance.
            </p>
          </section>

          {/* 12. Contact */}
          <section>
            <h2 className="mb-2 text-lg font-semibold text-text-primary">12. Contact</h2>
            <p>
              For questions about these terms, contact{' '}
              <a href="mailto:conduct@echolabsme.com" className="text-accent hover:text-accent-hover">
                conduct@echolabsme.com
              </a>.
            </p>
          </section>

        </div>
      </div>
    </div>
  );
}
